Repository jenkins-x-plugins/jx-gitops, pull requests merged in 2020-09, with the labels that each got.

#173 fix: avoid merging with terraform ConfigMap losing chartRepository
  pkg/cmd/requirement/merge/merge.go
  pkg/cmd/requirement/merge/test_data/expected.yml
  pkg/cmd/requirement/merge/test_data/jx-requirements.yml
Labels: approved, size/XS

#174 fix: avoid overwriting the gitServer
  jenkins-x.yml
  pkg/cmd/requirement/merge/merge.go
  pkg/cmd/requirement/merge/test_data/expected.yml
  pkg/cmd/requirement/merge/test_data/jx-requirements.yml
Labels: approved, size/S

#175 fix: lets default the pipeline user/email properly if not specified
  pkg/cmd/requirement/resolve/resolve.go
  pkg/cmd/requirement/resolve/resolve_test.go
  pkg/cmd/requirement/resolve/test_data/eks/jx-requirements.yml
  pkg/cmd/requirement/resolve/test_data/gke/jx-requirements.yml
Labels: approved, size/L

#176 fix: upgrade ot latest jx
  go.mod
  go.sum
  pkg/pipelinescheduler/config_builder.go
  pkg/pipelinescheduler/generator.go
  pkg/pipelinescheduler/scheduler_builder.go
Labels: size/L

#177 fix: resolve should ignore local charts
  pkg/cmd/helmfile/resolve/resolve.go
Labels: approved, size/L

#178 fix: handle relative charts in a parent dir
  pkg/cmd/helmfile/resolve/resolve.go
Labels: approved, size/XS

#179 fix: add helper command to rename yaml files
  pkg/cmd/rename/rename.go
  pkg/cmd/rename/rename_test.go
  pkg/cmd/rename/test_data/resource.yaml
  pkg/cmd/rename/test_data/resource10.yaml
  pkg/cmd/rename/test_data/resource11.yaml
  pkg/cmd/rename/test_data/resource12.yaml
  pkg/cmd/rename/test_data/resource13.yaml
  pkg/cmd/rename/test_data/resource14.yaml
  pkg/cmd/rename/test_data/resource15.yaml
  pkg/cmd/rename/test_data/resource16.yaml
  pkg/cmd/rename/test_data/resource17.yaml
  pkg/cmd/rename/test_data/resource18.yaml
  pkg/cmd/rename/test_data/resource19.yaml
  pkg/cmd/rename/test_data/resource2.yaml
  pkg/cmd/rename/test_data/resource20.yaml
  pkg/cmd/rename/test_data/resource21.yaml
  pkg/cmd/rename/test_data/resource22.yaml
  pkg/cmd/rename/test_data/resource23.yaml
  pkg/cmd/rename/test_data/resource24.yaml
  pkg/cmd/rename/test_data/resource25.yaml
  pkg/cmd/rename/test_data/resource26.yaml
  pkg/cmd/rename/test_data/resource27.yaml
  pkg/cmd/rename/test_data/resource28.yaml
  pkg/cmd/rename/test_data/resource29.yaml
  pkg/cmd/rename/test_data/resource3.yaml
  pkg/cmd/rename/test_data/resource30.yaml
  pkg/cmd/rename/test_data/resource31.yaml
  pkg/cmd/rename/test_data/resource32.yaml
  pkg/cmd/rename/test_data/resource33.yaml
  pkg/cmd/rename/test_data/resource34.yaml
  pkg/cmd/rename/test_data/resource35.yaml
  pkg/cmd/rename/test_data/resource36.yaml
  pkg/cmd/rename/test_data/resource37.yaml
  pkg/cmd/rename/test_data/resource38.yaml
  pkg/cmd/rename/test_data/resource39.yaml
  pkg/cmd/rename/test_data/resource4.yaml
  pkg/cmd/rename/test_data/resource40.yaml
  pkg/cmd/rename/test_data/resource41.yaml
  pkg/cmd/rename/test_data/resource42.yaml
  pkg/cmd/rename/test_data/resource43.yaml
  pkg/cmd/rename/test_data/resource5.yaml
  pkg/cmd/rename/test_data/resource6.yaml
  pkg/cmd/rename/test_data/resource7.yaml
  pkg/cmd/rename/test_data/resource8.yaml
  pkg/cmd/rename/test_data/resource9.yaml
  pkg/cmd/root.go
Labels: approved, size/XXL

#180 fix: goreleaser version
  .goreleaser.yml
Labels: approved, size/XS

#181 fix: lets make lots of output debug logging
  go.mod
  go.sum
  pkg/cmd/helmfile/template/template.go
Labels: approved, size/M

#183 fix: add a little helper command
  docs/cmd/jx-gitops.md
  docs/cmd/jx-gitops_annotate.md
  docs/cmd/jx-gitops_condition.md
  docs/cmd/jx-gitops_git.md
  docs/cmd/jx-gitops_git_get.md
  docs/cmd/jx-gitops_git_setup.md
  docs/cmd/jx-gitops_hash.md
  docs/cmd/jx-gitops_helm.md
  docs/cmd/jx-gitops_helm_stream.md
  docs/cmd/jx-gitops_helm_template.md
  docs/cmd/jx-gitops_helmfile.md
  docs/cmd/jx-gitops_helmfile_add.md
  docs/cmd/jx-gitops_helmfile_move.md
  docs/cmd/jx-gitops_helmfile_resolve.md
  docs/cmd/jx-gitops_helmfile_template.md
  docs/cmd/jx-gitops_image.md
  docs/cmd/jx-gitops_ingress.md
  docs/cmd/jx-gitops_kpt.md
  docs/cmd/jx-gitops_kpt_recreate.md
  docs/cmd/jx-gitops_kpt_update.md
  docs/cmd/jx-gitops_kustomize.md
  docs/cmd/jx-gitops_label.md
  docs/cmd/jx-gitops_namespace.md
  docs/cmd/jx-gitops_postprocess.md
  docs/cmd/jx-gitops_pr.md
  docs/cmd/jx-gitops_pr_get.md
  docs/cmd/jx-gitops_pr_push.md
  docs/cmd/jx-gitops_rename.md
  docs/cmd/jx-gitops_repository.md
  docs/cmd/jx-gitops_repository_create.md
  docs/cmd/jx-gitops_repository_export.md
  docs/cmd/jx-gitops_repository_resolve.md
  docs/cmd/jx-gitops_requirement.md
  docs/cmd/jx-gitops_requirement_edit.md
  docs/cmd/jx-gitops_requirement_merge.md
  docs/cmd/jx-gitops_requirement_resolve.md
  docs/cmd/jx-gitops_sa.md
  docs/cmd/jx-gitops_sa_secret.md
  docs/cmd/jx-gitops_scheduler.md
  docs/cmd/jx-gitops_split.md
  docs/cmd/jx-gitops_upgrade.md
  docs/cmd/jx-gitops_version.md
  docs/man/man1/jx-gitops-git-get.1
  docs/man/man1/jx-gitops-git.1
  go.mod
  go.sum
  pkg/cmd/git/get/get.go
  pkg/cmd/git/get/get_test.go
  pkg/cmd/git/get/test_data/myorg/myrepo/expected.txt
  pkg/cmd/git/git.go
Labels: approved, size/L

#184 fix: kpt caching issues when running multiple kpt pkg updates
  pkg/cmd/kpt/update/update.go
Labels: approved, lgtm, size/S

#186 fix: upgrade to git patch kpt upgrades
  Dockerfile
  Dockerfile-preview
  docs/cmd/jx-gitops_kpt_update.md
  docs/cmd/jx-gitops_upgrade.md
  go.mod
  go.sum
  jenkins-x.yml
  pkg/cmd/kpt/update/update.go
  pkg/cmd/kpt/update/update_test.go
  pkg/cmd/pr/push/push.go
Labels: approved, size/M

#188 fix: removed dead code
  go.mod
  pkg/authhelpers/helpers.go
  pkg/cmd/namespace/namespace.go
  pkg/cmd/pr/get/get.go
  pkg/cmd/pr/get/get_test.go
  pkg/cmd/pr/push/push.go
  pkg/cmd/pr/push/push_test.go
  pkg/cmd/requirement/edit/edit.go
  pkg/pipelinescheduler/generator.go
  pkg/pipelinescheduler/scheduler_builder.go
Labels: approved, size/XL

#189 fix: lazy create command runner
  pkg/cmd/pr/push/push.go
Labels: approved, size/XS

#190 fix: push to branch logic
  pkg/cmd/pr/push/push.go
Labels: approved, size/S

#193 fix: upgrade deps
  go.mod
  go.sum
Labels: approved, size/L

#195 fix: upgrade deps
  go.mod
  go.sum
Labels: approved, size/S

#197 fix: bug adding new repos
  go.mod
  go.sum
  pkg/cmd/repository/add/add.go
Labels: approved, size/S

#198 fix: lets handle more local repos better
  go.mod
  go.sum
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/helmhelpers/helpers.go
  pkg/helmhelpers/helpers_test.go
Labels: approved, size/M

#200 fix: enable in-repo-config generation for lighthouse
  pkg/cmd/scheduler/scheduler.go
  pkg/cmd/scheduler/scheduler_test.go
  pkg/cmd/scheduler/test_data/config-root/namespaces/jx/jxboot-helmfile-resources/default-scheduler.yaml
Labels: approved, size/S

#201 feat: allow a kp-strategy.yaml file to optinally define merge strategies for kpt to use on a foldler by folder basis
  Makefile
  docs/cmd/jx-gitops.md
  docs/cmd/jx-gitops_annotate.md
  docs/cmd/jx-gitops_condition.md
  docs/cmd/jx-gitops_git.md
  docs/cmd/jx-gitops_git_get.md
  docs/cmd/jx-gitops_git_setup.md
  docs/cmd/jx-gitops_hash.md
  docs/cmd/jx-gitops_helm.md
  docs/cmd/jx-gitops_helm_stream.md
  docs/cmd/jx-gitops_helm_template.md
  docs/cmd/jx-gitops_helmfile.md
  docs/cmd/jx-gitops_helmfile_add.md
  docs/cmd/jx-gitops_helmfile_move.md
  docs/cmd/jx-gitops_helmfile_resolve.md
  docs/cmd/jx-gitops_helmfile_template.md
  docs/cmd/jx-gitops_image.md
  docs/cmd/jx-gitops_ingress.md
  docs/cmd/jx-gitops_kpt.md
  docs/cmd/jx-gitops_kpt_recreate.md
  docs/cmd/jx-gitops_kpt_update.md
  docs/cmd/jx-gitops_kustomize.md
  docs/cmd/jx-gitops_label.md
  docs/cmd/jx-gitops_namespace.md
  docs/cmd/jx-gitops_postprocess.md
  docs/cmd/jx-gitops_pr.md
  docs/cmd/jx-gitops_pr_get.md
  docs/cmd/jx-gitops_pr_push.md
  docs/cmd/jx-gitops_rename.md
  docs/cmd/jx-gitops_repository.md
  docs/cmd/jx-gitops_repository_add.md
  docs/cmd/jx-gitops_repository_create.md
  docs/cmd/jx-gitops_repository_export.md
  docs/cmd/jx-gitops_repository_resolve.md
  docs/cmd/jx-gitops_requirement.md
  docs/cmd/jx-gitops_requirement_edit.md
  docs/cmd/jx-gitops_requirement_merge.md
  docs/cmd/jx-gitops_requirement_resolve.md
  docs/cmd/jx-gitops_sa.md
  docs/cmd/jx-gitops_sa_secret.md
  docs/cmd/jx-gitops_scheduler.md
  docs/cmd/jx-gitops_split.md
  docs/cmd/jx-gitops_upgrade.md
  docs/cmd/jx-gitops_version.md
  docs/config.md
  docs/kind_filters.md
  docs/man/man1/jx-gitops-kpt-update.1
  docs/man/man1/jx-gitops-upgrade.1
  go.mod
  go.sum
  pkg/apis/gitops/v1alpha1/kpt_strategy_types.go
  pkg/cmd/kpt/update/test_data/validate_fail/.jx/gitops/kpt-strategy.yaml
  pkg/cmd/kpt/update/test_data/validate_pass/.jx/gitops/kpt-strategy.yaml
  pkg/cmd/kpt/update/update.go
  pkg/cmd/kpt/update/update_test.go
Labels: approved, lgtm, size/XXL

#202 fix: avoid adding the default scheduler if there is another scheduler…
  pkg/cmd/scheduler/scheduler_test.go
  pkg/cmd/scheduler/test_data/config-root/namespaces/jx/jxboot-helmfile-resources/blank-scheduler.yaml
  pkg/cmd/scheduler/test_data/config-root/namespaces/jx/jxboot-helmfile-resources/in-repo-sr.yaml
  pkg/pipelinescheduler/generator.go
Labels: approved, size/M

#203 fix: support finding the boot secret in the operator namespace
  pkg/cmd/git/setup/setup.go
  pkg/cmd/git/setup/setup_test.go
Labels: approved, size/M

#205 fix: add variables command and fix helm release cmd
  docs/cmd/jx-gitops.md
  docs/cmd/jx-gitops_helm_release.md
  docs/cmd/jx-gitops_variables.md
  docs/config.md
  docs/man/man1/jx-gitops-helm-release.1
  docs/man/man1/jx-gitops-variables.1
  docs/man/man1/jx-gitops.1
  pkg/cmd/helm/release/release.go
  pkg/cmd/root.go
  pkg/cmd/variables/test_data/expected.sh
  pkg/cmd/variables/variables.go
  pkg/cmd/variables/variables_test.go
  pkg/variablefinders/variablefinders.go
Labels: approved, size/XL

#206 fix: add variables file to git fix: add variables command
  go.mod
  go.sum
  pkg/cmd/helm/release/release_test.go
  pkg/cmd/variables/variables.go
Labels: approved, size/S

#207 fix: add a more optimal apply command
  docs/cmd/jx-gitops.md
  docs/cmd/jx-gitops_annotate.md
  docs/cmd/jx-gitops_apply.md
  docs/cmd/jx-gitops_condition.md
  docs/cmd/jx-gitops_git.md
  docs/cmd/jx-gitops_git_get.md
  docs/cmd/jx-gitops_git_setup.md
  docs/cmd/jx-gitops_hash.md
  docs/cmd/jx-gitops_helm.md
  docs/cmd/jx-gitops_helm_release.md
  docs/cmd/jx-gitops_helm_stream.md
  docs/cmd/jx-gitops_helm_template.md
  docs/cmd/jx-gitops_helmfile.md
  docs/cmd/jx-gitops_helmfile_add.md
  docs/cmd/jx-gitops_helmfile_move.md
  docs/cmd/jx-gitops_helmfile_resolve.md
  docs/cmd/jx-gitops_helmfile_template.md
  docs/cmd/jx-gitops_image.md
  docs/cmd/jx-gitops_ingress.md
  docs/cmd/jx-gitops_kpt.md
  docs/cmd/jx-gitops_kpt_recreate.md
  docs/cmd/jx-gitops_kpt_update.md
  docs/cmd/jx-gitops_kustomize.md
  docs/cmd/jx-gitops_label.md
  docs/cmd/jx-gitops_namespace.md
  docs/cmd/jx-gitops_postprocess.md
  docs/cmd/jx-gitops_pr.md
  docs/cmd/jx-gitops_pr_get.md
  docs/cmd/jx-gitops_pr_push.md
  docs/cmd/jx-gitops_rename.md
  docs/cmd/jx-gitops_repository.md
  docs/cmd/jx-gitops_repository_add.md
  docs/cmd/jx-gitops_repository_create.md
  docs/cmd/jx-gitops_repository_export.md
  docs/cmd/jx-gitops_repository_resolve.md
  docs/cmd/jx-gitops_requirement.md
  docs/cmd/jx-gitops_requirement_edit.md
  docs/cmd/jx-gitops_requirement_merge.md
  docs/cmd/jx-gitops_requirement_resolve.md
  docs/cmd/jx-gitops_sa.md
  docs/cmd/jx-gitops_sa_secret.md
  docs/cmd/jx-gitops_scheduler.md
  docs/cmd/jx-gitops_split.md
  docs/cmd/jx-gitops_upgrade.md
  docs/cmd/jx-gitops_variables.md
  docs/cmd/jx-gitops_version.md
  docs/config.md
  docs/man/man1/jx-gitops-apply.1
  docs/man/man1/jx-gitops.1
  pkg/cmd/apply/apply.go
  pkg/cmd/root.go
Labels: approved, size/L

#208 fix: add better PR logic for apply
  pkg/cmd/apply/apply.go
Labels: approved, size/M

#210 fix: fix up variable unit test by providing fake scmclient
  pkg/cmd/variables/variables_test.go
Labels: approved, lgtm, ok-to-test, size/XS

#211 fix: align scheduler structures with LH
  pkg/cmd/helmfile/move/test_data/output/helmfile-b22978a4-jxboot-helmfile-resources/jxboot-helmfile-resources/templates/default-scheduler.yaml
  pkg/cmd/helmfile/move/test_data/output/helmfile-b22978a4-jxboot-helmfile-resources/jxboot-helmfile-resources/templates/env-scheduler.yaml
  pkg/cmd/helmfile/move/test_data/output/helmfile-b22978a4-jxboot-helmfile-resources/jxboot-helmfile-resources/templates/pr-only-scheduler.yaml
  pkg/cmd/helmfile/move/test_data/output/helmfile-b22978a4-jxboot-helmfile-resources/jxboot-helmfile-resources/templates/release-only-scheduler.yaml
  pkg/cmd/repository/add/add.go
  pkg/cmd/repository/export/export.go
  pkg/cmd/scheduler/scheduler.go
  pkg/cmd/scheduler/test_data/versionStream/schedulers/default.yaml
  pkg/cmd/scheduler/test_data/versionStream/schedulers/environment.yaml
  pkg/cmd/scheduler/test_data/versionStream/schedulers/in-repo.yaml
  pkg/cmd/scheduler/test_data/versionStream/schedulers/jx-meta-pipeline.yaml
  pkg/pipelinescheduler/builder.go
  pkg/pipelinescheduler/config_builder.go
  pkg/pipelinescheduler/config_builder_test.go
  pkg/pipelinescheduler/scheduler_builder.go
  pkg/pipelinescheduler/test_data/merger_with_mergemethod/config.yaml
  pkg/pipelinescheduler/test_data/merger_with_mergemethod/parent.yaml
  pkg/pipelinescheduler/test_data/merger_with_mergemethod/plugins.yaml
  pkg/pipelinescheduler/test_data/merger_with_mergemethod/repo.yaml
  pkg/pipelinescheduler/test_data/merger_with_parent/config.yaml
  pkg/pipelinescheduler/test_data/merger_with_parent/parent.yaml
  pkg/pipelinescheduler/test_data/merger_with_parent/plugins.yaml
  pkg/pipelinescheduler/test_data/merger_with_parent/repo.yaml
  pkg/pipelinescheduler/test_data/multiple_contexts/config.yaml
  pkg/pipelinescheduler/test_data/multiple_contexts/repo.yaml
  pkg/pipelinescheduler/test_data/no_postsubmits_with_parent/config.yaml
  pkg/pipelinescheduler/test_data/no_postsubmits_with_parent/parent.yaml
  pkg/pipelinescheduler/test_data/no_postsubmits_with_parent/plugins.yaml
  pkg/pipelinescheduler/test_data/no_postsubmits_with_parent/repo.yaml
  pkg/pipelinescheduler/test_data/only_plugins/parent.yaml
  pkg/pipelinescheduler/test_data/only_plugins/plugins.yaml
  pkg/pipelinescheduler/test_data/only_plugins/repo.yaml
  pkg/pipelinescheduler/test_data/only_plugins_from_parent/parent.yaml
  pkg/pipelinescheduler/test_data/only_plugins_from_parent/plugins.yaml
  pkg/pipelinescheduler/test_data/only_plugins_from_repo/plugins.yaml
  pkg/pipelinescheduler/test_data/only_plugins_from_repo/repo.yaml
  pkg/pipelinescheduler/test_data/only_with_parent/config.yaml
  pkg/pipelinescheduler/test_data/only_with_parent/parent.yaml
  pkg/pipelinescheduler/test_data/only_with_parent/plugins.yaml
  pkg/pipelinescheduler/test_data/policy_with_parent/config.yaml
  pkg/pipelinescheduler/test_data/policy_with_parent/parent.yaml
  pkg/pipelinescheduler/test_data/policy_with_parent/plugins.yaml
  pkg/pipelinescheduler/test_data/policy_with_parent/repo.yaml
  pkg/pipelinescheduler/test_data/repo/config.yaml
  pkg/pipelinescheduler/test_data/repo/repo.yaml
  pkg/pipelinescheduler/test_data/with_parent/config.yaml
  pkg/pipelinescheduler/test_data/with_parent/parent.yaml
  pkg/pipelinescheduler/test_data/with_parent/plugins.yaml
  pkg/pipelinescheduler/test_data/with_parent/repo.yaml
  pkg/pipelinescheduler/testhelpers/helpers.go
  pkg/schedulerapi/types.go
  pkg/sourceconfigs/helpers.go
Labels: approved, size/XXL

#212 fix: add support for templating urls
  go.mod
  go.sum
  pkg/cmd/scheduler/scheduler.go
  pkg/cmd/scheduler/scheduler_test.go
  pkg/cmd/scheduler/templater.go
  pkg/cmd/scheduler/test_data/jx-requirements.yml
  pkg/cmd/scheduler/test_data/versionStream/schedulers/default.yaml
  pkg/cmd/scheduler/test_data/versionStream/schedulers/environment.yaml
  pkg/cmd/scheduler/test_data/versionStream/schedulers/in-repo.yaml
  pkg/cmd/scheduler/test_data/versionStream/schedulers/jx-meta-pipeline.yaml
  pkg/pipelinescheduler/builder.go
  pkg/pipelinescheduler/config_builder_test.go
  pkg/pipelinescheduler/test_data/policy_with_parent/parent.yaml
Labels: approved, size/L

#213 fix: lets log the variable values
  pkg/cmd/variables/variables.go
Labels: approved, size/XS

#221 fix: better detection of PullRequest for variables
  pkg/variablefinders/version.go
Labels: approved, size/XS

#222 fix: add better default preview version
  pkg/variablefinders/version.go
Labels: approved, size/XS

#223 feat: Add pr comment functionality
  pkg/cmd/pr/comment/comment.go
  pkg/cmd/pr/pr.go
Labels: approved, lgtm, ok-to-test, size/M

#224 fix: add better diagnostics if we cannot find the version file
  docs/cmd/jx-gitops.md
  docs/cmd/jx-gitops_annotate.md
  docs/cmd/jx-gitops_apply.md
  docs/cmd/jx-gitops_condition.md
  docs/cmd/jx-gitops_git.md
  docs/cmd/jx-gitops_git_get.md
  docs/cmd/jx-gitops_git_setup.md
  docs/cmd/jx-gitops_hash.md
  docs/cmd/jx-gitops_helm.md
  docs/cmd/jx-gitops_helm_release.md
  docs/cmd/jx-gitops_helm_stream.md
  docs/cmd/jx-gitops_helm_template.md
  docs/cmd/jx-gitops_helmfile.md
  docs/cmd/jx-gitops_helmfile_add.md
  docs/cmd/jx-gitops_helmfile_move.md
  docs/cmd/jx-gitops_helmfile_resolve.md
  docs/cmd/jx-gitops_helmfile_template.md
  docs/cmd/jx-gitops_image.md
  docs/cmd/jx-gitops_ingress.md
  docs/cmd/jx-gitops_kpt.md
  docs/cmd/jx-gitops_kpt_recreate.md
  docs/cmd/jx-gitops_kpt_update.md
  docs/cmd/jx-gitops_kustomize.md
  docs/cmd/jx-gitops_label.md
  docs/cmd/jx-gitops_namespace.md
  docs/cmd/jx-gitops_postprocess.md
  docs/cmd/jx-gitops_pr.md
  docs/cmd/jx-gitops_pr_get.md
  docs/cmd/jx-gitops_pr_push.md
  docs/cmd/jx-gitops_rename.md
  docs/cmd/jx-gitops_repository.md
  docs/cmd/jx-gitops_repository_add.md
  docs/cmd/jx-gitops_repository_create.md
  docs/cmd/jx-gitops_repository_export.md
  docs/cmd/jx-gitops_repository_resolve.md
  docs/cmd/jx-gitops_requirement.md
  docs/cmd/jx-gitops_requirement_edit.md
  docs/cmd/jx-gitops_requirement_merge.md
  docs/cmd/jx-gitops_requirement_resolve.md
  docs/cmd/jx-gitops_sa.md
  docs/cmd/jx-gitops_sa_secret.md
  docs/cmd/jx-gitops_scheduler.md
  docs/cmd/jx-gitops_split.md
  docs/cmd/jx-gitops_upgrade.md
  docs/cmd/jx-gitops_variables.md
  docs/cmd/jx-gitops_version.md
  docs/config.md
  docs/man/man1/jx-gitops-apply.1
  docs/man/man1/jx-gitops-scheduler.1
  docs/man/man1/jx-gitops-variables.1
  pkg/cmd/helm/release/release.go
Labels: approved, size/L

#225 fix: improve variables discovery
  go.mod
  go.sum
  pkg/cmd/variables/variables.go
  pkg/variablefinders/version.go
Labels: approved, size/S

#226 fix: add an extra env var for meta pipeline
  pkg/cmd/variables/test_data/expected.sh
  pkg/cmd/variables/variables.go
  pkg/variablefinders/pipeline_kind.go
Labels: approved, size/S

#227 fix: lets create better in repo config
  pkg/cmd/scheduler/scheduler.go
  pkg/cmd/scheduler/scheduler_test.go
Labels: approved, size/S

#228 fix: avoid overwriting git config if running pipelines locally
  go.mod
  go.sum
  pkg/cmd/git/setup/setup.go
Labels: approved, size/XS

#229 fix: add a better BUILD_NUMBER generator
  go.mod
  go.sum
  pkg/cmd/variables/variables.go
  pkg/cmd/variables/variables_test.go
Labels: approved, size/L

#233 fix: for GitKind discovery
  go.mod
  go.sum
  pkg/cmd/repository/create/create.go
  pkg/cmd/repository/create/create_test.go
  pkg/cmd/repository/create/test_data/expected/config-root/namespaces/jx/source-repositories/mygitlaborg-somegitlab.yaml
  pkg/cmd/repository/create/test_data/input/.jx/gitops/source-config.yaml
Labels: approved, size/M

#234 fix: ensure the add repository command populates gitKind/gitProvider
  go.mod
  go.sum
  pkg/cmd/repository/add/add.go
  pkg/cmd/repository/add/add_test.go
  pkg/cmd/repository/add/test_data/anewthingy/.jx/gitops/source-config.yaml
  pkg/cmd/repository/add/test_data/anewthingy/expected.yaml
  pkg/cmd/repository/add/test_data/anewthingy/jx-requirements.yml
  pkg/cmd/repository/add/test_data/mygitlab/.jx/gitops/source-config.yaml
  pkg/cmd/repository/add/test_data/mygitlab/expected.yaml
  pkg/cmd/repository/add/test_data/mygitlab/jx-requirements.yml
  pkg/cmd/repository/export/export.go
  pkg/sourceconfigs/helpers.go
Labels: approved, size/L

#239 fix: support separate ingress domain / subdomain per namespace
  pkg/cmd/helmfile/template/template.go
  pkg/jxtmpl/reqvalues/requirements_values.go
Labels: approved, size/M
