Repository jenkins-x-plugins/jx-gitops, pull requests merged in 2020-10, with the labels that each got.

#241 fix: allow push PR errors to be ignored if not on a PR
  Makefile
  cloudbuild.yaml
  go.mod
  go.sum
  pkg/cmd/pr/push/push.go
Labels: approved, size/M

#244 fix: lets move the repo/merge/context options out of presubmits
  pkg/cmd/scheduler/scheduler_test.go
  pkg/cmd/scheduler/test_data/versionStream/schedulers/default.yaml
  pkg/cmd/scheduler/test_data/versionStream/schedulers/environment.yaml
  pkg/cmd/scheduler/test_data/versionStream/schedulers/in-repo.yaml
  pkg/cmd/scheduler/test_data/versionStream/schedulers/jx-meta-pipeline.yaml
  pkg/pipelinescheduler/builder.go
  pkg/pipelinescheduler/config_builder.go
  pkg/pipelinescheduler/scheduler_builder.go
  pkg/pipelinescheduler/test_data/merger_with_mergemethod/parent.yaml
  pkg/pipelinescheduler/test_data/merger_with_parent/parent.yaml
  pkg/pipelinescheduler/test_data/multiple_contexts/repo.yaml
  pkg/pipelinescheduler/test_data/no_postsubmits_with_parent/parent.yaml
  pkg/pipelinescheduler/test_data/only_with_parent/parent.yaml
  pkg/pipelinescheduler/test_data/policy_with_parent/parent.yaml
  pkg/pipelinescheduler/test_data/repo/repo.yaml
  pkg/pipelinescheduler/test_data/with_parent/parent.yaml
  pkg/pipelinescheduler/testhelpers/helpers.go
  pkg/schedulerapi/types.go
Labels: approved, size/XL

#245 fix: remove temporary files
  pkg/cmd/helmfile/template/template.go
Labels: approved, size/XS

#246 fix: avoid failing on: 'jx gitops pr push' if on master
  go.mod
  go.sum
  pkg/cmd/pr/push/push.go
Labels: approved, size/L

#250 fix: add a more meaningful error if we can't list webhooks
  pkg/cmd/webhook/verify/verify.go
Labels: approved, size/XS

#254 fix: only perform custom upgrades if update mode
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/cmd/helmfile/resolve/resolve_test.go
Labels: approved, size/M

#255 fix: only add remote helm repos if they are not added
  go.sum
  pkg/helmhelpers/helpers.go
Labels: approved, size/S

#258 fix: only run helmfile resolve if we have a helmfile
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/cmd/upgrade/upgrade.go
Labels: approved, size/S

#262 fix: remove local boot secret
  go.mod
  go.sum
  pkg/boot/boot_secret.go
  pkg/boot/boot_secret_test.go
  pkg/cmd/git/setup/setup.go
Labels: approved, size/M

#264 fix: avoid bug missing out regen-phase-2
  pkg/cmd/apply/apply.go
Labels: approved, size/S

#267 fix: avoid possible empty annotations map
  pkg/cmd/webhook/verify/verify.go
Labels: approved, size/XS

#276 fix: avoid logging user/token
  go.mod
  go.sum
  pkg/cmd/repository/resolve/resolve.go
Labels: approved, size/S

#279 chore: use the release name to resove values files, which defaults to the chart name if release name is not set, which keeps existing behaviour.
  go.sum
  pkg/cmd/helmfile/resolve/resolve.go
Labels: approved, size/XS

#280 chore: also use the release name to resolve defaults like namespace if present in the version stream, defaults to the chart name if release name is not set which keeping existing behaviour.
  pkg/cmd/helmfile/resolve/resolve.go
Labels: approved, size/XS

#281 chore: if the release name is different from a previous chart of the same name then lets add it as not a duplicate
  jenkins-x.yml
  pkg/cmd/helmfile/add/add.go
Labels: approved, size/XS

#283 chore: fix failing release test
  pkg/variablefinders/repo_url.go
Labels: approved, size/XS

#284 fix: improve finding of the build number
  pkg/cmd/variables/variables.go
Labels: approved, size/M

#285 fix: use correct selector for finding existing builds
  pkg/cmd/variables/variables.go
Labels: approved, size/XS

#286 fix: use quiet runner
  pkg/cmd/postprocess/postprocess.go
Labels: approved, size/XS

#288 fix: lets handle branch names which don't map to selectors
  go.mod
  go.sum
  pkg/cmd/variables/variables.go
Labels: approved, size/M

#293 fix: allow custom scheduler directory
  docs/cmd/jx-gitops.md
  docs/cmd/jx-gitops_annotate.md
  docs/cmd/jx-gitops_apply.md
  docs/cmd/jx-gitops_condition.md
  docs/cmd/jx-gitops_git.md
  docs/cmd/jx-gitops_git_get.md
  docs/cmd/jx-gitops_git_setup.md
  docs/cmd/jx-gitops_hash.md
  docs/cmd/jx-gitops_helm.md
  docs/cmd/jx-gitops_helm_release.md
  docs/cmd/jx-gitops_helm_stream.md
  docs/cmd/jx-gitops_helm_template.md
  docs/cmd/jx-gitops_helmfile.md
  docs/cmd/jx-gitops_helmfile_add.md
  docs/cmd/jx-gitops_helmfile_move.md
  docs/cmd/jx-gitops_helmfile_resolve.md
  docs/cmd/jx-gitops_helmfile_template.md
  docs/cmd/jx-gitops_image.md
  docs/cmd/jx-gitops_ingress.md
  docs/cmd/jx-gitops_jenkins.md
  docs/cmd/jx-gitops_jenkins_release.md
  docs/cmd/jx-gitops_kpt.md
  docs/cmd/jx-gitops_kpt_recreate.md
  docs/cmd/jx-gitops_kpt_update.md
  docs/cmd/jx-gitops_kustomize.md
  docs/cmd/jx-gitops_label.md
  docs/cmd/jx-gitops_namespace.md
  docs/cmd/jx-gitops_postprocess.md
  docs/cmd/jx-gitops_pr.md
  docs/cmd/jx-gitops_pr_comment.md
  docs/cmd/jx-gitops_pr_get.md
  docs/cmd/jx-gitops_pr_push.md
  docs/cmd/jx-gitops_rename.md
  docs/cmd/jx-gitops_repository.md
  docs/cmd/jx-gitops_repository_add.md
  docs/cmd/jx-gitops_repository_create.md
  docs/cmd/jx-gitops_repository_export.md
  docs/cmd/jx-gitops_repository_resolve.md
  docs/cmd/jx-gitops_requirement.md
  docs/cmd/jx-gitops_requirement_edit.md
  docs/cmd/jx-gitops_requirement_merge.md
  docs/cmd/jx-gitops_requirement_publish.md
  docs/cmd/jx-gitops_requirement_resolve.md
  docs/cmd/jx-gitops_sa.md
  docs/cmd/jx-gitops_sa_secret.md
  docs/cmd/jx-gitops_scheduler.md
  docs/cmd/jx-gitops_split.md
  docs/cmd/jx-gitops_upgrade.md
  docs/cmd/jx-gitops_variables.md
  docs/cmd/jx-gitops_version.md
  docs/cmd/jx-gitops_webhook.md
  docs/cmd/jx-gitops_webhook_update.md
  docs/config.md
  docs/man/man1/jx-gitops-scheduler.1
  docs/man/man1/jx-gitops-webhook-update.1
  pkg/cmd/scheduler/scheduler.go
Labels: approved

#300 fix: use quiet command logger
  pkg/cmd/helm/release/release.go
Labels: approved, size/XS

#303 fix: allow tekton-secret mode
  go.mod
  go.sum
  pkg/cmd/git/setup/setup.go
Labels: approved, size/M

#301 chore: fix commit msg "added variables" to be aligned with Conventional Commits
  pkg/cmd/variables/variables.go
Labels: approved, lgtm, ok-to-test

#312 fix: fix issue with not clearing the correct kpt cache when running in a tekton pipeline
  pkg/cmd/kpt/update/update.go
Labels: approved, size/XS

#314 fix: use the helm plugin when upgrading git repos
  docs/cmd/jx-gitops_helmfile_resolve.md
  docs/cmd/jx-gitops_helmfile_template.md
  docs/cmd/jx-gitops_pr_label.md
  docs/config.md
  docs/man/man1/jx-gitops-helmfile-resolve.1
  docs/man/man1/jx-gitops-helmfile-template.1
  docs/man/man1/jx-gitops-pr-label.1
  go.mod
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/cmd/helmfile/resolve/resolve_test.go
  pkg/cmd/helmfile/template/template.go
  pkg/cmd/kpt/update/update.go
  pkg/cmd/pr/label/label.go
  pkg/cmd/upgrade/upgrade.go
  pkg/helmhelpers/helpers.go
  pkg/versionstreamer/versionstreamer.go
Labels: approved, size/M

#318 fix: upgrade helm
  go.mod
  go.sum
  pkg/plugins/versions.go
Labels: approved, size/L

#319 chore: lets automatically upgrade old stable chart repository
  docs/cmd/jx-gitops.md
  docs/cmd/jx-gitops_annotate.md
  docs/cmd/jx-gitops_apply.md
  docs/cmd/jx-gitops_condition.md
  docs/cmd/jx-gitops_copy.md
  docs/cmd/jx-gitops_git.md
  docs/cmd/jx-gitops_git_get.md
  docs/cmd/jx-gitops_git_setup.md
  docs/cmd/jx-gitops_hash.md
  docs/cmd/jx-gitops_helm.md
  docs/cmd/jx-gitops_helm_build.md
  docs/cmd/jx-gitops_helm_release.md
  docs/cmd/jx-gitops_helm_stream.md
  docs/cmd/jx-gitops_helm_template.md
  docs/cmd/jx-gitops_helmfile.md
  docs/cmd/jx-gitops_helmfile_add.md
  docs/cmd/jx-gitops_helmfile_move.md
  docs/cmd/jx-gitops_helmfile_resolve.md
  docs/cmd/jx-gitops_helmfile_template.md
  docs/cmd/jx-gitops_image.md
  docs/cmd/jx-gitops_ingress.md
  docs/cmd/jx-gitops_jenkins.md
  docs/cmd/jx-gitops_jenkins_release.md
  docs/cmd/jx-gitops_kpt.md
  docs/cmd/jx-gitops_kpt_recreate.md
  docs/cmd/jx-gitops_kpt_update.md
  docs/cmd/jx-gitops_kustomize.md
  docs/cmd/jx-gitops_label.md
  docs/cmd/jx-gitops_namespace.md
  docs/cmd/jx-gitops_postprocess.md
  docs/cmd/jx-gitops_pr.md
  docs/cmd/jx-gitops_pr_comment.md
  docs/cmd/jx-gitops_pr_get.md
  docs/cmd/jx-gitops_pr_label.md
  docs/cmd/jx-gitops_pr_push.md
  docs/cmd/jx-gitops_rename.md
  docs/cmd/jx-gitops_repository.md
  docs/cmd/jx-gitops_repository_add.md
  docs/cmd/jx-gitops_repository_create.md
  docs/cmd/jx-gitops_repository_export.md
  docs/cmd/jx-gitops_repository_resolve.md
  docs/cmd/jx-gitops_requirement.md
  docs/cmd/jx-gitops_requirement_edit.md
  docs/cmd/jx-gitops_requirement_merge.md
  docs/cmd/jx-gitops_requirement_publish.md
  docs/cmd/jx-gitops_requirement_resolve.md
  docs/cmd/jx-gitops_sa.md
  docs/cmd/jx-gitops_sa_secret.md
  docs/cmd/jx-gitops_scheduler.md
  docs/cmd/jx-gitops_split.md
  docs/cmd/jx-gitops_upgrade.md
  docs/cmd/jx-gitops_variables.md
  docs/cmd/jx-gitops_version.md
  docs/cmd/jx-gitops_webhook.md
  docs/cmd/jx-gitops_webhook_update.md
  docs/config.md
  pkg/cmd/helmfile/resolve/resolve.go
Labels: approved, size/L

#322 fix: lets override the versionStream/schedulers files with schedulers
  pkg/cmd/scheduler/scheduler.go
  pkg/cmd/scheduler/scheduler_test.go
  pkg/cmd/scheduler/test_data/config-root/namespaces/jx/jxboot-helmfile-resources/another-in-repo-sr.yaml
  pkg/cmd/scheduler/test_data/versionStream/schedulers/another-in-repo.yaml
  pkg/pipelinescheduler/builder.go
  pkg/pipelinescheduler/scheduler_builder.go
  pkg/pipelinescheduler/testhelpers/helpers.go
  pkg/schedulerapi/types.go
Labels: approved, size/L
