Repository jenkins-x-plugins/jx-gitops, pull requests merged in 2020-11, with the labels that each got.

#329 fix: improve the variables step
  .lighthouse/jenkins-x/release.yaml
  pkg/cmd/variables/test_data/tests/empty/expected.sh
  pkg/cmd/variables/test_data/tests/existing/.jx/variables.sh
  pkg/cmd/variables/test_data/tests/existing/expected.sh
  pkg/cmd/variables/variables.go
  pkg/cmd/variables/variables_test.go
Labels: approved, size/L

#331 Revert "fix: improve the variables step"
  .lighthouse/jenkins-x/release.yaml
  pkg/cmd/variables/test_data/expected.sh
  pkg/cmd/variables/test_data/tests/existing/.jx/variables.sh
  pkg/cmd/variables/test_data/tests/existing/expected.sh
  pkg/cmd/variables/variables.go
  pkg/cmd/variables/variables_test.go
Labels: approved, size/L

#333 fix: improve the variables step
  .lighthouse/jenkins-x/release.yaml
  go.mod
  go.sum
  pkg/cmd/variables/test_data/tests/empty/expected.sh
  pkg/cmd/variables/test_data/tests/existing/.jx/variables.sh
  pkg/cmd/variables/test_data/tests/existing/expected.sh
  pkg/cmd/variables/variables.go
  pkg/cmd/variables/variables_test.go
Labels: approved, size/L

#335 fix: improve discovery of environment git repository
  pkg/cmd/git/get/get.go
Labels: approved, size/S

#338 chore: lets replace the domain if it is changed in terraform
  go.sum
  pkg/cmd/requirement/merge/merge.go
  pkg/cmd/requirement/merge/test_data/changes.yml
  pkg/cmd/requirement/merge/test_data/expected.yml
Labels: approved, size/XS

#339 feat: Added in helmfile compatible conditional values for use in condition parameter of helmfile
  pkg/jxtmpl/reqvalues/requirements_values.go
Labels: approved, lgtm, ok-to-test, size/S

#340 chore: replace external dns flag if changes by terraform
  pkg/cmd/requirement/merge/merge.go
Labels: approved, lgtm, ok-to-test, size/XS

#341 chore: bumped jx-api version
  OWNERS
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test, size/XS

#343 fix: add binary plugin upgrade
  pkg/cmd/plugin/plugin.go
  pkg/cmd/plugin/upgrade/upgrade.go
  pkg/cmd/root.go
  pkg/cmd/webhook/verify/verify.go
  pkg/plugins/helpers.go
  pkg/plugins/helpers_test.go
  pkg/plugins/versions.go
Labels: approved, size/L

#344 fix: add plugin list command
  pkg/cmd/plugin/get/get.go
  pkg/cmd/plugin/plugin.go
  pkg/plugins/helpers.go
  pkg/plugins/helpers_test.go
  pkg/plugins/versions.go
Labels: approved, size/L

#347 fix: disable kpt for plugin download
  pkg/plugins/versions.go
Labels: approved, size/XS

#348 fix: default the chart repository
  pkg/cmd/requirement/resolve/resolve.go
  pkg/cmd/requirement/resolve/resolve_test.go
Labels: approved, size/S

#349 fix: downgrade helmfile
  pkg/plugins/versions.go
Labels: approved, size/XS

#351 fix: avoid space in chart repo URL
  pkg/cmd/requirement/resolve/resolve.go
  pkg/cmd/requirement/resolve/resolve_test.go
Labels: approved, size/XS

#353 fix: migrate from old jx-labs charts to jx3
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/cmd/helmfile/resolve/test_data/input/helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/.jx/gitops/secret-mappings.yaml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/expected-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/jx-requirements.yml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/values/external-dns/values.yaml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/values/kubernetes-external-secrets/values.yaml.gotmpl
  pkg/cmd/helmfile/resolve/test_data/local-secrets/versionStream/charts/banzaicloud-stable/vault-operator/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/versionStream/charts/bitnami/external-dns/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/versionStream/charts/bitnami/external-dns/template-values.yaml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/versionStream/charts/cdf/tekton-pipeline/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/versionStream/charts/cdf/tekton-pipeline/values.yaml.gotmpl
  pkg/cmd/helmfile/resolve/test_data/local-secrets/versionStream/charts/external-secrets/kubernetes-external-secrets/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/versionStream/charts/jenkins-x/jxboot-helmfile-resources/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/versionStream/charts/jenkins-x/lighthouse/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/versionStream/charts/jenkins-x/tekton/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/versionStream/charts/jenkins-x/tekton/values.yaml.gotmpl
  pkg/cmd/helmfile/resolve/test_data/local-secrets/versionStream/charts/jx3/jenkins-x-crds/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/versionStream/charts/jx3/jenkins-x-crds/values.yaml.gotmpl
  pkg/cmd/helmfile/resolve/test_data/local-secrets/versionStream/charts/jx3/local-external-secrets/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/versionStream/charts/repositories.yml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/versionStream/charts/repositories/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/versionStream/charts/stable/cert-manager/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/versionStream/charts/stable/chartmuseum/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/versionStream/charts/stable/chartmuseum/secret-schema.yaml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/versionStream/charts/stable/chartmuseum/values.yaml.gotmpl
  pkg/cmd/kpt/update/update.go
  pkg/plugins/helpers.go
  pkg/plugins/helpers_test.go
  pkg/plugins/versions.go
Labels: approved, size/L

#357 fix: handle missing scheduler for Environment SR
  pkg/cmd/scheduler/scheduler.go
  pkg/cmd/scheduler/test_data/config-root/namespaces/jx/jxboot-helmfile-resources/dev-env-sr.yaml
  pkg/cmd/scheduler/test_data/config-root/namespaces/jx/jxboot-helmfile-resources/devenv.yaml
Labels: approved, size/S

#358 fix: default to in repo scheduler for environments
  pkg/cmd/scheduler/scheduler.go
  pkg/cmd/scheduler/scheduler_test.go
Labels: approved, size/S

#361 fix: handle different case in kpt error messages
  pkg/cmd/kpt/update/update.go
Labels: approved, size/XS

#362 fix: work around kpt getting a merge conflict on Kptfile
  pkg/cmd/kpt/update/update.go
Labels: approved, size/M

#366 feat: extended move so that it separates out CRDs from cluster resources for scenarios where cluster resources depend on CRDs
  go.mod
  go.sum
  pkg/cmd/helmfile/move/move.go
  pkg/cmd/helmfile/move/move_test.go
  pkg/cmd/helmfile/template/template_test.go
Labels: approved, ok-to-test, size/M

#365 fix: issue not including the default version stream strategy if folks supply their own strategy file
  pkg/cmd/kpt/update/update.go
  pkg/cmd/kpt/update/update_test.go
Labels: approved, size/S

#368 fix: generate the correct job file name
  pkg/cmd/helmfile/resolve/resolve.go
Labels: approved, size/XS

#369 fix: lets resolve version stream versions and values for helm charts that use a chart name and also alias
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/cmd/webhook/verify/verify.go
Labels: approved, size/M

#370 fix: lets migrate to the new external secrets chart
  go.mod
  go.sum
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/cmd/helmfile/template/test_data/helmfile.yaml
Labels: approved, size/S

#377 fix: default mink environment variables
  go.mod
  go.sum
  pkg/cmd/variables/test_data/tests/empty/expected.sh
  pkg/cmd/variables/test_data/tests/existing/expected.sh
  pkg/cmd/variables/variables.go
Labels: approved, size/M

#384 chore: bump helmfile version
  go.mod
  go.sum
  pkg/cmd/helmfile/add/test_data/input/expected-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/bucketrepo-svc/expected-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/input/expected-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/expected-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/no-versionstream/expected-helmfile.yaml
  pkg/cmd/helmfile/template/template.go
  pkg/plugins/versions.go
Labels: approved, lgtm, ok-to-test, size/L

#388 fix: add escape command
  pkg/cmd/helm/escape/espape.go
  pkg/cmd/helm/escape/espape_test.go
  pkg/cmd/helm/escape/test_data/expected/config-observability-cm.yaml
  pkg/cmd/helm/escape/test_data/src/config-observability-cm.yaml
  pkg/cmd/helm/helm.go
Labels: approved, size/L

#390 feat: added in retries for webhook update command
  go.mod
  go.sum
  pkg/cmd/webhook/verify/verify.go
  pkg/cmd/webhook/webhook.go
Labels: approved, lgtm, ok-to-test, size/S
