Repository jenkins-x-plugins/jx-gitops, pull requests merged in 2020-12, with the labels that each got.

#392 chore: avoid warning if a chart version is specified
  go.sum
  pkg/cmd/helmfile/resolve/resolve.go
Labels: approved, lgtm, size/XS

#393 fix: add fix for mixed case organisations/repos
  go.mod
  go.sum
  pkg/cmd/variables/variables.go
Labels: approved, size/S

#399 refactor: move traditional CRDs back to jenkins.io group so we dont need to create new CRDs
  go.mod
  pkg/cmd/git/get/get.go
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/cmd/repository/create/create.go
  pkg/cmd/repository/export/export.go
  pkg/cmd/repository/export/export_test.go
  pkg/cmd/requirement/publish/publish.go
  pkg/cmd/requirement/publish/publish_test.go
  pkg/cmd/requirement/resolve/resolve_test.go
  pkg/cmd/requirement/resolve/test_data/backwards_compatible_requirements_file/new/jx-requirements.yml
  pkg/cmd/scheduler/scheduler.go
  pkg/cmd/variables/variables.go
  pkg/cmd/variables/variables_test.go
  pkg/cmd/webhook/verify/verify.go
  pkg/cmd/webhook/verify/verify_test.go
  pkg/pipelinescheduler/generator.go
  pkg/pipelinescheduler/scheduler_builder.go
  pkg/pipelinescheduler/source_repositories.go
  pkg/plugins/helpers.go
  pkg/plugins/versions.go
Labels: approved, size/M

#400 fix: possible nil pointer exception
  go.mod
  go.sum
  pkg/cmd/helmfile/template/template.go
Labels: approved, size/M

#402 fix: upgrade to latest deps
  go.mod
  go.sum
  pkg/apis/gitops/v1alpha1/pipeline_catalog_types.go
  pkg/cmd/helm/release/release.go
  pkg/cmd/helm/release/release_test.go
  pkg/cmd/requirement/publish/publish_test.go
  pkg/cmd/requirement/resolve/resolve_test.go
  pkg/cmd/variables/variables.go
  pkg/cmd/variables/variables_test.go
  pkg/pipelinecatalogs/pipelinecatalogs.go
  pkg/plugins/helpers_test.go
  pkg/variablefinders/requirements.go
Labels: approved, size/L

#404 fix: for downloading arm binaries
  pkg/plugins/helpers.go
Labels: approved, size/S

#405 chore(variables): add arg to skip committing `variables.sh`
  pkg/cmd/variables/variables.go
Labels: approved, lgtm, ok-to-test, size/S

#407 fix: handle arm64 binaries of helmfile
  pkg/cmd/helm/release/release_test.go
  pkg/cmd/variables/test_data/tests/empty/expected.sh
  pkg/cmd/variables/test_data/tests/existing/expected.sh
  pkg/cmd/variables/variables_test.go
  pkg/fakerunners/git_cloner.go
  pkg/plugins/helpers.go
  pkg/plugins/helpers_test.go
Labels: approved, size/M

#408 chore: upgrade pipelines
  .lighthouse/jenkins-x/Kptfile
Labels: size/S, updatebot

#410 fix: fixed up regression of helmfile args being removed from helmfile template command
  pkg/cmd/helmfile/template/template.go
  pkg/cmd/helmfile/template/template_test.go
  pkg/cmd/helmfile/template/test_data/basic/jx-values.yaml
  pkg/cmd/helmfile/template/test_data/nested/jx-values.yaml
Labels: approved, lgtm, ok-to-test, size/L

#406 feat: added in retry on error behaviour for some requirements k8s based commands that occasionally timeout during boot jobs
  pkg/cmd/requirement/requirement.go
Labels: approved, lgtm, ok-to-test, size/XS

#411 fix: issue with helmfile template in BDD, it seems values files should be passed as flags to the main template command rather than using the --args flag
  pkg/cmd/helmfile/template/template.go
Labels: approved, lgtm, size/XS

#412 fix: removed args input to jx gitops helmfile template as this is redundant now in helmfile template. Replaced with a values file input that accepts multiple files on the command line
  go.mod
  go.sum
  pkg/cmd/helmfile/template/template.go
  pkg/cmd/helmfile/template/template_test.go
Labels: approved, ok-to-test, size/S

#413 fix: upgrade to latest helmfile arm binary
  go.mod
  go.sum
  pkg/plugins/helpers.go
  pkg/plugins/helpers_test.go
Labels: approved, size/S

#414 fix: use the correct arm download url
  pkg/plugins/helpers.go
  pkg/plugins/helpers_test.go
Labels: approved, size/XS

#387 fix: custom helmfile upgrade for new nginx chart
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/cmd/helmfile/resolve/test_data/input/expected-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/input/expected-nginx-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/input/helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/input/versionStream/charts/ingress-nginx/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/input/versionStream/charts/ingress-nginx/values.yaml.gotmpl
Labels: approved, lgtm, size/M

#416 fix: support separate ingress domain per namespace
  pkg/cmd/helmfile/add/add.go
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/cmd/helmfile/resolve/test_data/bucketrepo-svc/expected-jx-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/bucketrepo-svc/expected-tekton-pipelines-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/input/expected-foo-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/input/expected-jx-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/input/expected-secret-infra-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/input/expected-tekton-pipelines-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/expected-jx-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/expected-secret-infra-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/expected-tekton-pipelines-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/no-versionstream/expected-external-secrets-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/no-versionstream/expected-foo-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/no-versionstream/expected-jx-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/no-versionstream/expected-tekton-pipelines-helmfile.yaml
  pkg/helmhelpers/helpers_test.go
  pkg/jxtmpl/reqvalues/requirements_values.go
Labels: approved, size/L

#417 fix: always regenerate the helmfile jx-values.yaml
  pkg/cmd/helmfile/resolve/resolve.go
Labels: approved, size/XS

#418 fix: regression in upgrading to nginx
  pkg/cmd/helmfile/resolve/resolve.go
Labels: approved, size/XS

#420 fix: fixed up resolve so it is savvy enough to know whether it runs pre or post helmfile structure
  pkg/cmd/helmfile/resolve/resolve.go
Labels: approved, lgtm, ok-to-test, size/S

#421 fix: better upgrade of nginx value templates file
  go.mod
  go.sum
  pkg/cmd/helmfile/add/add.go
  pkg/cmd/helmfile/add/add_test.go
  pkg/cmd/helmfile/add/test_data/input/expected-helmfile.yaml
  pkg/cmd/helmfile/helmfile.go
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/cmd/helmfile/template/template.go
  pkg/cmd/helmfile/template/template_test.go
  pkg/cmd/helmfile/template/test_data/basic/.jx/gitops/secret-mappings.yaml
  pkg/cmd/helmfile/template/test_data/basic/helmfile.yaml
  pkg/cmd/helmfile/template/test_data/basic/jx-requirements.yml
  pkg/cmd/helmfile/template/test_data/basic/jx-values.yaml
  pkg/cmd/helmfile/template/test_data/nested/helmfile.yaml
  pkg/cmd/helmfile/template/test_data/nested/helmfiles/jx-production/helmfile.yaml
  pkg/cmd/helmfile/template/test_data/nested/helmfiles/jx/helmfile.yaml
  pkg/cmd/helmfile/template/test_data/nested/helmfiles/secret-infra/helmfile.yaml
  pkg/cmd/helmfile/template/test_data/nested/jx-requirements.yml
  pkg/cmd/helmfile/template/test_data/nested/jx-values.yaml
Labels: approved, size/XL

#422 fix: rmeove old jx-values.yaml file
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/cmd/helmfile/resolve/resolve_test.go
  pkg/cmd/helmfile/resolve/test_data/input/imagePullSecrets.yaml
Labels: approved, size/M

#423 chore: add command to switch version streams
  go.sum
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/cmd/kpt/update/update.go
  pkg/cmd/kpt/update/update_test.go
  pkg/cmd/root.go
  pkg/cmd/versionstream/test_data/custom/expected
  pkg/cmd/versionstream/test_data/custom/versionStream/Kptfile
  pkg/cmd/versionstream/test_data/latest/expected
  pkg/cmd/versionstream/test_data/latest/versionStream/Kptfile
  pkg/cmd/versionstream/test_data/lts/expected
  pkg/cmd/versionstream/test_data/lts/versionStream/Kptfile
  pkg/cmd/versionstream/versionstream.go
  pkg/cmd/versionstream/versionstream_test.go
  pkg/versionstreamer/versionstreamer.go
Labels: approved, size/XL

#428 fix: erroneous repository being added if using local charts
  pkg/cmd/helmfile/structure/structure.go
Labels: approved, size/XS

#429 chore: make sure email is merged if set
  pkg/cmd/requirement/merge/merge.go
Labels: approved, size/XS

#430 chore: bumped helmfile so we can omit empty helmfile values
  go.mod
  go.sum
  pkg/cmd/helmfile/add/test_data/input/expected-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/bucketrepo-svc/expected-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/bucketrepo-svc/expected-jx-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/bucketrepo-svc/expected-tekton-pipelines-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/input/expected-foo-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/input/expected-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/input/expected-jx-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/input/expected-nginx-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/input/expected-secret-infra-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/input/expected-tekton-pipelines-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/expected-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/expected-jx-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/expected-secret-infra-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/expected-tekton-pipelines-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/no-versionstream/expected-external-secrets-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/no-versionstream/expected-foo-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/no-versionstream/expected-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/no-versionstream/expected-jx-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/no-versionstream/expected-tekton-pipelines-helmfile.yaml
  pkg/cmd/helmfile/structure/test_data/expected-helmfile.yaml
  pkg/cmd/helmfile/structure/test_data/helmfiles/jx/expected-helmfile.yaml
  pkg/cmd/helmfile/structure/test_data/helmfiles/tekton-pipelines/expected-helmfile.yaml
Labels: approved, lgtm, ok-to-test, size/L

#432 chore: bump jx-api version
  go.mod
  go.sum
  pkg/cmd/requirement/merge/test_data/changes.yml
  pkg/cmd/requirement/merge/test_data/expected.yml
Labels: approved, lgtm, ok-to-test, size/S

#433 feat: replaced custom merge with an all encompassing one
  go.mod
  pkg/cmd/requirement/merge/merge.go
  pkg/cmd/requirement/merge/test_data/expected.yml
Labels: approved, lgtm, ok-to-test, size/M

#434 chore: bump jx-api version
  go.mod
Labels: approved, lgtm, ok-to-test, size/XS

#435 fix: preserve the custom domain or sub domain from requirements
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/cmd/helmfile/resolve/resolve_test.go
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/.jx/gitops/secret-mappings.yaml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/expected-foo-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/expected-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/expected-jx-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/expected-jx-staging-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/expected-nginx-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/expected-secret-infra-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/expected-tekton-pipelines-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/extensions/pipeline-catalog.yaml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/imagePullSecrets.yaml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/jx-requirements.yml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/values/external-dns/values.yaml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/values/kubernetes-external-secrets/values.yaml.gotmpl
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/versionStream/charts/banzaicloud-stable/vault-operator/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/versionStream/charts/bitnami/external-dns/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/versionStream/charts/bitnami/external-dns/template-values.yaml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/versionStream/charts/cdf/tekton-pipeline/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/versionStream/charts/cdf/tekton-pipeline/values.yaml.gotmpl
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/versionStream/charts/external-secrets/kubernetes-external-secrets/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/versionStream/charts/ingress-nginx/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/versionStream/charts/ingress-nginx/values.yaml.gotmpl
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/versionStream/charts/jenkins-x/jxboot-helmfile-resources/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/versionStream/charts/jenkins-x/lighthouse/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/versionStream/charts/jenkins-x/tekton/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/versionStream/charts/jenkins-x/tekton/values.yaml.gotmpl
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/versionStream/charts/repositories.yml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/versionStream/charts/repositories/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/versionStream/charts/stable/cert-manager/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/versionStream/charts/stable/chartmuseum/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/versionStream/charts/stable/chartmuseum/secret-schema.yaml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/versionStream/charts/stable/chartmuseum/values.yaml.gotmpl
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/versionStream/git/github.com/jenkins-x/jx3-pipeline-catalog.yml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/versionStream/git/github.com/jstrachan/jx3-pipeline-catalog.yml
  pkg/jxtmpl/reqvalues/requirements_values.go
  pkg/plugins/helpers.go
  pkg/plugins/helpers_test.go
  pkg/plugins/versions.go
Labels: approved, size/XL

#436 chore: add more tests for the terraform requirements merge
  go.sum
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/cmd/helmfile/resolve/resolve_test.go
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/expected-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/jx-requirements.yml
  pkg/cmd/requirement/merge/merge_test.go
  pkg/cmd/requirement/merge/test_data/azure/changes.yml
  pkg/cmd/requirement/merge/test_data/azure/expected.yml
  pkg/cmd/requirement/merge/test_data/azure/jx-requirements.yml
  pkg/cmd/requirement/merge/test_data/eks/changes.yml
  pkg/cmd/requirement/merge/test_data/eks/expected.yml
  pkg/cmd/requirement/merge/test_data/eks/jx-requirements.yml
  pkg/cmd/requirement/merge/test_data/gke-no-domain/changes.yml
  pkg/cmd/requirement/merge/test_data/gke-no-domain/expected.yml
  pkg/cmd/requirement/merge/test_data/gke-no-domain/jx-requirements.yml
  pkg/cmd/requirement/merge/test_data/gke/changes.yml
  pkg/cmd/requirement/merge/test_data/gke/expected.yml
  pkg/cmd/requirement/merge/test_data/gke/jx-requirements.yml
  pkg/cmd/requirement/merge/test_data/sample/changes.yml
  pkg/cmd/requirement/merge/test_data/sample/expected.yml
  pkg/cmd/requirement/merge/test_data/sample/jx-requirements.yml
Labels: approved, size/XL

#440 chore: helmfile mod bump
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test, size/S

#439 feat: added resolve logic to determine enviromment owner from git if possible
  pkg/cmd/requirement/resolve/resolve.go
Labels: approved, lgtm, ok-to-test, size/S

#442 fix: fixed up retriable commands that were not passing error back out to wrapper function
  pkg/cmd/requirement/merge/merge.go
  pkg/cmd/requirement/resolve/resolve.go
Labels: approved, lgtm, ok-to-test, size/S

#443 chore: ugprade deps
  go.mod
  go.sum
Labels: approved, size/S

#449 fixx: first spike of a git rebase/merge command
  go.mod
  go.sum
  pkg/cmd/git/git.go
  pkg/cmd/git/merge/merge.go
  pkg/cmd/git/merge/merge_shas.go
  pkg/cmd/git/merge/merge_test.go
  pkg/cmd/git/merge/pull_refs.go
  pkg/cmd/git/merge/pull_refs_test.go
Labels: approved, size/XL

#450 fix: added kapp support
  pkg/plugins/versions.go
Labels: approved, size/XS

#456 fix: use the latest chart values.yaml for jenkins jobs
  pkg/cmd/jenkins/jobs/jobs.go
  pkg/cmd/jenkins/jobs/test_data/.jx/gitops/source-config.yaml
Labels: approved, size/S

#457 fix: switch to using Jenkins JobDSL for importing jobs
  pkg/apis/gitops/v1alpha1/source_config_types.go
  pkg/cmd/jenkins/jobs/jobs.go
  pkg/cmd/jenkins/jobs/test_data/jenkins/templates/default.job.gotmpl
  pkg/cmd/jenkins/jobs/test_data/jenkins/templates/default.xml.gotmpl
Labels: approved, size/L

#458 fix: use better job yaml
  pkg/cmd/jenkins/jobs/jobs.go
  pkg/cmd/jenkins/jobs/jobs_test.go
  pkg/cmd/jenkins/jobs/test_data/hasjobs/.jx/gitops/source-config.yaml
  pkg/cmd/jenkins/jobs/test_data/hasjobs/jenkins/templates/default.job.gotmpl
  pkg/cmd/jenkins/jobs/test_data/nojobs/.jx/gitops/source-config.yaml
Labels: approved, size/M

#461 fix: support jenkins templates for folders too
  go.mod
  go.sum
  pkg/apis/gitops/v1alpha1/source_config_types.go
  pkg/cmd/jenkins/add/add.go
  pkg/cmd/jenkins/jobs/jobs.go
  pkg/cmd/jenkins/jobs/test_data/hasjobs/jenkins/templates/folder.gotmpl
  pkg/cmd/jenkins/jobs/test_data/hasjobs/jenkins/templates/job.gotmpl
Labels: approved, size/L

#462 fix: lets only upgrade if git is clean
  pkg/cmd/kpt/update/update.go
  pkg/cmd/kpt/update/update_test.go
Labels: approved, size/S

#463 fix: move the quickstart parsing code here
  pkg/apis/gitops/v1alpha1/quickstart_types.go
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/cmd/helmfile/resolve/resolve_test.go
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/extensions/quickstarts.yaml
  pkg/matcher/matcher.go
  pkg/quickstarthelpers/load.go
Labels: approved, size/L

#464 fix: lets add the jenkins version stream config
  pkg/cmd/jenkins/jobs/jobs.go
Labels: approved, size/S

#465 fix: lets use helmfile resolve to add custom config
  pkg/cmd/jenkins/jobs/jobs.go
Labels: approved, size/S

#466 fix: lets add extra jenkins resources by default
  pkg/cmd/apply/apply.go
  pkg/cmd/jenkins/add/add.go
Labels: approved, size/S

#467 fix: polish the log output
  go.mod
  go.sum
  pkg/cmd/repository/export/export.go
Labels: approved, size/S

#469 fix: ensure we have a valid branch for gitops variables
  pkg/cmd/variables/variables.go
Labels: approved, size/XS

#470 fix: adding a jenkins server adds an entry in the source config
  go.mod
  go.sum
  pkg/cmd/jenkins/add/add.go
  pkg/cmd/jenkins/add/add_test.go
  pkg/cmd/jenkins/add/test_data/helmfile.yaml
  pkg/cmd/jenkins/add/test_data/jx-requirements.yml
  pkg/cmd/jenkins/add/test_data/versionStream/charts/repositories.yml
  pkg/cmd/jenkins/jobs/jobs.go
  pkg/sourceconfigs/helpers.go
Labels: approved, size/L

#478 fix: add jenkins add command
  docs/cmd/jx-gitops_jenkins.md
  docs/cmd/jx-gitops_jenkins_add.md
  docs/config.md
  docs/man/man1/jx-gitops-jenkins-add.1
  docs/man/man1/jx-gitops-jenkins.1
  pkg/cmd/jenkins/jenkins.go
Labels: approved, size/L

#477 fix: gitea webhook update creating duplicate hooks
  pkg/cmd/webhook/verify/verify.go
Labels: approved, lgtm, ok-to-test, size/XS

#479 chore: jx-helpers bump
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test, size/XS

#482 chore: temporarily switched kapp across to fork
  pkg/cmd/variables/variables.go
  pkg/plugins/helpers.go
  pkg/plugins/helpers_test.go
  pkg/plugins/versions.go
Labels: approved, ok-to-test, size/S

#483 fix: helm lint should be called after dependency build
  pkg/cmd/helm/release/release.go
Labels: approved, lgtm, ok-to-test, size/XS

#485 feat: added in OCI registry push to helm release
  pkg/cmd/helm/release/release.go
Labels: approved, lgtm, ok-to-test, size/L

#491 chore: upgrade dependencies
  go.mod
  go.sum
Labels: approved, size/M
