Repository jenkins-x-plugins/jx-gitops, pull requests merged in 2020-07, with the labels that each got.

#70 fix: add command to resolve missing GKE metadata
  docs/cmd/jx-gitops.md
  docs/cmd/jx-gitops_annotate.md
  docs/cmd/jx-gitops_apps.md
  docs/cmd/jx-gitops_apps_resolve.md
  docs/cmd/jx-gitops_apps_template.md
  docs/cmd/jx-gitops_condition.md
  docs/cmd/jx-gitops_extsecret.md
  docs/cmd/jx-gitops_git.md
  docs/cmd/jx-gitops_git_setup.md
  docs/cmd/jx-gitops_hash.md
  docs/cmd/jx-gitops_helm.md
  docs/cmd/jx-gitops_helm_stream.md
  docs/cmd/jx-gitops_helm_template.md
  docs/cmd/jx-gitops_ingress.md
  docs/cmd/jx-gitops_kpt.md
  docs/cmd/jx-gitops_kpt_recreate.md
  docs/cmd/jx-gitops_kpt_update.md
  docs/cmd/jx-gitops_kustomize.md
  docs/cmd/jx-gitops_label.md
  docs/cmd/jx-gitops_namespace.md
  docs/cmd/jx-gitops_pr.md
  docs/cmd/jx-gitops_pr_get.md
  docs/cmd/jx-gitops_pr_push.md
  docs/cmd/jx-gitops_repository.md
  docs/cmd/jx-gitops_scheduler.md
  docs/cmd/jx-gitops_split.md
  docs/cmd/jx-gitops_version.md
  docs/config.md
  docs/man/man1/jx-gitops.1
  go.mod
  pkg/cmd/helm/step_helm_stream_test.go
  pkg/cmd/pr/get/get.go
  pkg/cmd/requirement/requirement.go
  pkg/cmd/requirement/resolve/gke.go
  pkg/cmd/requirement/resolve/resolve.go
  pkg/cmd/requirement/resolve/resolve_test.go
  pkg/cmd/requirement/resolve/test_data/jx-requirements.yml
  pkg/cmd/root.go
Labels: approved, size/L

#71 fix: add a command to edit requirements
  docs/cmd/jx-gitops_requirement.md
  docs/cmd/jx-gitops_requirement_edit.md
  docs/cmd/jx-gitops_requirement_resolve.md
  docs/config.md
  docs/man/man1/jx-gitops-requirement-edit.1
  docs/man/man1/jx-gitops-requirement-resolve.1
  docs/man/man1/jx-gitops-requirement.1
  pkg/cmd/requirement/edit/edit.go
  pkg/cmd/requirement/edit/edit_test.go
  pkg/cmd/requirement/edit/test_data/gitops-enabled.yml
  pkg/cmd/requirement/requirement.go
Labels: approved, size/XL

#72 fix: git add before commit
  pkg/cmd/requirement/resolve/gke.go
Labels: size/XS

#73 fix: some gremlins on the apps resolve
  pkg/cmd/apps/resolve/resolve.go
  pkg/cmd/apps/resolve/test_data/expected-jx-apps.yml
  pkg/jxtmpl/reqvalues/requirements_values.go
Labels: approved, size/S

#76 feat: support google secrets manager in secrets mapping
  go.mod
  pkg/apis/gitops/v1alpha1/types.go
  pkg/cmd/extsecret/extsecret.go
  pkg/cmd/extsecret/extsecret_test.go
  pkg/cmd/extsecret/gsm/helper.go
  pkg/cmd/extsecret/test_data/backend_types/.jx/gitops/secret-mappings.yaml
  pkg/cmd/extsecret/test_data/backend_types/oauth2/expected.yaml
  pkg/cmd/extsecret/test_data/backend_types/oauth2/source.yaml
Labels: approved, lgtm, size/L

#85 fix: add support for modifying Jobs
  Dockerfile
  docs/cmd/jx-gitops.md
  docs/cmd/jx-gitops_annotate.md
  docs/cmd/jx-gitops_apps.md
  docs/cmd/jx-gitops_apps_resolve.md
  docs/cmd/jx-gitops_apps_template.md
  docs/cmd/jx-gitops_condition.md
  docs/cmd/jx-gitops_extsecret.md
  docs/cmd/jx-gitops_git.md
  docs/cmd/jx-gitops_git_setup.md
  docs/cmd/jx-gitops_hash.md
  docs/cmd/jx-gitops_helm.md
  docs/cmd/jx-gitops_helm_stream.md
  docs/cmd/jx-gitops_helm_template.md
  docs/cmd/jx-gitops_image.md
  docs/cmd/jx-gitops_ingress.md
  docs/cmd/jx-gitops_kpt.md
  docs/cmd/jx-gitops_kpt_recreate.md
  docs/cmd/jx-gitops_kpt_update.md
  docs/cmd/jx-gitops_kustomize.md
  docs/cmd/jx-gitops_label.md
  docs/cmd/jx-gitops_namespace.md
  docs/cmd/jx-gitops_pr.md
  docs/cmd/jx-gitops_pr_get.md
  docs/cmd/jx-gitops_pr_push.md
  docs/cmd/jx-gitops_repository.md
  docs/cmd/jx-gitops_requirement.md
  docs/cmd/jx-gitops_requirement_edit.md
  docs/cmd/jx-gitops_requirement_resolve.md
  docs/cmd/jx-gitops_scheduler.md
  docs/cmd/jx-gitops_split.md
  docs/cmd/jx-gitops_version.md
  docs/config.md
  docs/man/man1/jx-gitops-image.1
  docs/man/man1/jx-gitops.1
  go.mod
  go.sum
  pkg/cmd/image/image.go
  pkg/cmd/image/image_test.go
  pkg/cmd/image/test_data/expected/jx-requirements.yml
  pkg/cmd/image/test_data/expected/src/deployment.yaml
  pkg/cmd/image/test_data/expected/src/job.yaml
  pkg/cmd/image/test_data/expected/src/pipelinerun-with-task.yml
  pkg/cmd/image/test_data/expected/src/tasks.yaml
  pkg/cmd/image/test_data/input/jx-requirements.yml
  pkg/cmd/image/test_data/input/src/deployment.yaml
  pkg/cmd/image/test_data/input/src/job.yaml
  pkg/cmd/image/test_data/input/src/pipelinerun-with-task.yml
  pkg/cmd/image/test_data/input/src/tasks.yaml
  pkg/cmd/image/test_data/versionstream/docker/gcr.io/jenkinsxio/jx-cli.yml
  pkg/cmd/image/test_data/versionstream/docker/gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init.yml
  pkg/cmd/image/test_data/versionstream/docker/ubuntu.yml
  pkg/cmd/label/label.go
  pkg/cmd/namespace/namespace.go
  pkg/cmd/root.go
  pkg/pipelinescheduler/config_builder.go
  pkg/pipelinescheduler/generator.go
  pkg/pipelinescheduler/scheduler_builder.go
  pkg/pipelinescheduler/testhelpers/helpers.go
  pkg/versionstreamer/versionstreamer.go
Labels: approved, size/XXL
