Repository jenkins-x-plugins/jx-gitops, pull requests merged in 2021-07, with the labels that each got.

#785 fix: compatible regen-phase with gitlab
  pkg/cmd/apply/apply.go
Labels: approved, lgtm, ok-to-test, size/XS

#787 fix: if we change an ExternalSecret lets force a full regenerate
  pkg/cmd/apply/apply.go
Labels: approved, size/M

#788 fix: upgrade helm and helmfile
  Makefile
  fns/label/Dockerfile
  fns/label/Dockerfile-generated
  fns/label/main.go
  go.mod
  go.sum
  pkg/plugins/versions.go
Labels: approved, size/L

#789 feat: jx gitops webhook delete
  pkg/cmd/webhook/delete/delete.go
  pkg/cmd/webhook/webhook.go
Labels: approved, lgtm, ok-to-test, size/L

#790 fix: avoid colon in PR labels causing issues
  go.sum
  pkg/cmd/helmfile/resolve/resolve_test.go
  pkg/cmd/helmfile/resolve/test_data/helmfile_multi_subfolder/expected-kuberhealthy-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_multi_subfolder/helmfiles/kuberhealthy/helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_multi_subfolder/versionStream/charts/jxgh/jx-kh-check/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_multi_subfolder/versionStream/charts/jxgh/jx-kh-check/values.yaml.gotmpl
  pkg/cmd/helmfile/resolve/test_data/helmfile_multi_subfolder/versionStream/charts/jxgh/kh-tls-check/defaults.yaml
  pkg/cmd/pr/variables/test_data/empty/expected.sh
  pkg/cmd/pr/variables/test_data/existing/expected.sh
  pkg/cmd/pr/variables/variables.go
  pkg/cmd/pr/variables/variables_test.go
Labels: approved, size/M

#791 chore: add helm repos before helm build
  pkg/chart/chart.go
  pkg/cmd/helm/build/build.go
  pkg/cmd/helm/release/release.go
Labels: approved, lgtm, ok-to-test, size/M

#792 fix: ToLower on repo name so that chart museum doesn't error
  pkg/cmd/variables/variables.go
Labels: approved, lgtm, ok-to-test, size/XS

#795 fix: add CLI: jx gitops repository delete
  docs/cmd/jx-gitops_helmfile_delete.md
  docs/cmd/jx-gitops_repository.md
  docs/cmd/jx-gitops_repository_delete.md
  docs/cmd/jx-gitops_webhook_delete.md
  docs/config.md
  docs/man/man1/jx-gitops-helmfile-delete.1
  docs/man/man1/jx-gitops-repository-delete.1
  docs/man/man1/jx-gitops-repository.1
  docs/man/man1/jx-gitops-webhook-delete.1
  docs/scheduler-config.md
  pkg/cmd/helmfile/deletecmd/delete.go
  pkg/cmd/repository/deletecmd/delete.go
  pkg/cmd/repository/deletecmd/delete_test.go
  pkg/cmd/repository/deletecmd/test_data/simple-owner/.jx/gitops/source-config.yaml
  pkg/cmd/repository/deletecmd/test_data/simple-owner/expected.yaml
  pkg/cmd/repository/deletecmd/test_data/simple/.jx/gitops/source-config.yaml
  pkg/cmd/repository/deletecmd/test_data/simple/expected.yaml
  pkg/cmd/repository/repository.go
  pkg/sourceconfigs/helpers.go
Labels: approved, size/XL

#796 fix: polish docs
  docs/cmd/jx-gitops_helmfile_delete.md
  docs/cmd/jx-gitops_repository_delete.md
  docs/config.md
  docs/man/man1/jx-gitops-helmfile-delete.1
  docs/man/man1/jx-gitops-repository-delete.1
  docs/scheduler-config.md
  pkg/cmd/helmfile/deletecmd/delete.go
  pkg/cmd/repository/deletecmd/delete.go
Labels: approved, size/M

#797 fix: when upgrading remote repos don't add build-controller
  go.mod
  go.sum
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/cmd/helmfile/resolve/resolve_test.go
  pkg/cmd/helmfile/resolve/test_data/bucketrepo-svc/expected-jx-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/bucketrepo-svc/helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_remote/expected-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_remote/expected-jx-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_remote/expected-secret-infra-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_remote/helmfiles/helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_remote/helmfiles/jx/helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_remote/helmfiles/jx/jx-values.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_remote/helmfiles/secret-infra/helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_remote/imagePullSecrets.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_remote/jx-requirements.yml
  pkg/cmd/helmfile/resolve/test_data/helmfile_remote/versionStream/charts/external-secrets/kubernetes-external-secrets/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_remote/versionStream/charts/jxgh/jx-build-controller/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_remote/versionStream/charts/jxgh/jx-build-controller/values.yaml.gotmpl
  pkg/cmd/helmfile/resolve/test_data/helmfile_remote/versionStream/charts/jxgh/lighthouse/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_remote/versionStream/charts/jxgh/lighthouse/secret-schema.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_remote/versionStream/charts/jxgh/lighthouse/values.yaml.gotmpl
  pkg/cmd/helmfile/resolve/test_data/helmfile_remote/versionStream/charts/repositories.yml
  pkg/cmd/helmfile/resolve/test_data/helmfile_remote/versionStream/git/github.com/jenkins-x/jx3-pipeline-catalog.yml
  pkg/cmd/helmfile/resolve/test_data/helmfile_remote/versionStream/git/github.com/jstrachan/jx3-pipeline-catalog.yml
Labels: approved, size/L
