Repository jenkins-x-plugins/jx-gitops, pull requests merged in 2021-05, with the labels that each got.

#749 fix: warn instead of fail if 'jx gitops variables' is run in a folder without git
  pkg/cmd/variables/variables.go
Labels: approved, lgtm, ok-to-test, size/XS

#751 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/S

#750 fix: return empty string instead of the error message if not in a git directory
  pkg/cmd/variables/variables.go
Labels: approved, lgtm, ok-to-test, size/XS

#752 fix: handle remote charts
  go.mod
  go.sum
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/cmd/helmfile/resolve/resolve_test.go
  pkg/cmd/helmfile/resolve/test_data/remote-chart/.jx/gitops/secret-mappings.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-chart/expected-foo-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-chart/expected-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-chart/expected-jx-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-chart/expected-nginx-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-chart/expected-secret-infra-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-chart/expected-tekton-pipelines-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-chart/extensions/pipeline-catalog.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-chart/helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-chart/imagePullSecrets.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-chart/jx-requirements.yml
  pkg/cmd/helmfile/resolve/test_data/remote-chart/values/external-dns/values.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-chart/values/kubernetes-external-secrets/values.yaml.gotmpl
  pkg/cmd/helmfile/resolve/test_data/remote-chart/versionStream/charts/banzaicloud-stable/vault-operator/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-chart/versionStream/charts/bitnami/external-dns/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-chart/versionStream/charts/bitnami/external-dns/template-values.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-chart/versionStream/charts/cdf/tekton-pipeline/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-chart/versionStream/charts/cdf/tekton-pipeline/values.yaml.gotmpl
  pkg/cmd/helmfile/resolve/test_data/remote-chart/versionStream/charts/external-secrets/kubernetes-external-secrets/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-chart/versionStream/charts/ingress-nginx/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-chart/versionStream/charts/ingress-nginx/values.yaml.gotmpl
  pkg/cmd/helmfile/resolve/test_data/remote-chart/versionStream/charts/jenkins-x/jxboot-helmfile-resources/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-chart/versionStream/charts/jenkins-x/lighthouse/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-chart/versionStream/charts/jenkins-x/tekton/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-chart/versionStream/charts/jenkins-x/tekton/values.yaml.gotmpl
  pkg/cmd/helmfile/resolve/test_data/remote-chart/versionStream/charts/repositories.yml
  pkg/cmd/helmfile/resolve/test_data/remote-chart/versionStream/charts/repositories/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-chart/versionStream/charts/stable/cert-manager/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-chart/versionStream/charts/stable/chartmuseum/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-chart/versionStream/charts/stable/chartmuseum/secret-schema.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-chart/versionStream/charts/stable/chartmuseum/values.yaml.gotmpl
  pkg/cmd/helmfile/resolve/test_data/remote-chart/versionStream/git/github.com/jenkins-x/jx3-pipeline-catalog.yml
  pkg/cmd/helmfile/resolve/test_data/remote-chart/versionStream/git/github.com/jstrachan/jx3-pipeline-catalog.yml
  pkg/cmd/webhook/update/update.go
Labels: approved, size/L

#754 fix: avoid populating timestamps for relative or remote charts
  pkg/cmd/helmfile/report/report.go
  pkg/helmhelpers/helpers.go
Labels: approved, size/M

#755 fix: upgrade to the latest helmfile
  Dockerfile
  go.mod
  go.sum
  pkg/plugins/versions.go
Labels: approved, size/M

#758 fix: support update only mode
  go.mod
  go.sum
  pkg/helmfiles/add.go
Labels: approved, size/XS

#759 fix: better defaulting of git user/email from requirements
  go.mod
  go.sum
  pkg/cmd/git/setup/setup.go
Labels: approved, size/M

#760 fix: lets allow the requirements to be passed in
  pkg/cmd/git/setup/setup.go
Labels: approved, size/M

#762 fix: add upgrade migration from old kuberhealthy chart
  go.mod
  go.sum
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/cmd/helmfile/resolve/resolve_test.go
  pkg/cmd/helmfile/resolve/test_data/helmfile_multi_subfolder/expected-kuberhealthy-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_multi_subfolder/helmfiles/helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_multi_subfolder/helmfiles/kuberhealthy/helmfile.yaml
  pkg/cmd/repository/create/create_test.go
Labels: approved, size/L

#761 feat: Add mlprojectsets
  pkg/apis/gitops/v1alpha1/quickstart_types.go
Labels: approved, lgtm, ok-to-test, size/XS

#763 fix: lets disable helmfile repos
  pkg/cmd/helmfile/resolve/resolve.go
Labels: approved, size/M

#764 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/S

#766 chore: Move submitted doucmentation changes frox jx-docs to jx-gitops source code
  pkg/cmd/git/clone/clone.go
  pkg/cmd/git/get/get.go
  pkg/cmd/git/merge/merge.go
  pkg/cmd/git/setup/setup.go
Labels: approved, lgtm, ok-to-test, size/M

#767 fix: upgrade to new bucketrepo chart
  go.mod
  go.sum
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/cmd/helmfile/resolve/test_data/bucketrepo-svc/expected-jx-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/bucketrepo-svc/helmfile.yaml
Labels: approved, size/M

#768 fix: make group owner lowercase for comparison
  pkg/sourceconfigs/helpers.go
Labels: approved, lgtm, size/XS

#771 chore: ugprade deps
  go.mod
  go.sum
Labels: approved, size/M
