Repository jenkins-x-plugins/jx-gitops, pull requests merged in 2021-12, with the labels that each got.

#820 fix: set valid label value for nested gitlab repository
  OWNERS
  go.mod
  go.sum
  pkg/cmd/repository/create/create.go
  pkg/cmd/repository/create/create_test.go
  pkg/cmd/repository/create/test_data/expected/config-root/namespaces/jx/source-repositories/jx-gitlab-test-cluster-gitlab-import-test-1.yaml
  pkg/cmd/repository/create/test_data/input/.jx/gitops/source-config.yaml
  pkg/cmd/repository/resolve/resolve.go
Labels: size/M, approved

#822 chore: bump lighthouse client to 0.0.295
  go.mod
  go.sum
Labels: approved, size/XS

#823 fix: eks git ops tf upgrade
  pkg/tfupgrade/test_data/eks/expected.tf
  pkg/tfupgrade/test_data/eks/main.tf
  pkg/tfupgrade/test_data/eks/versionStream/git/github.com/jenkins-x/terraform-aws-eks-jx.yml
  pkg/tfupgrade/tfupgrade.go
  pkg/tfupgrade/tfupgrade_test.go
Labels: size/M, approved

#824 feat: add gc jobs
  docs/cmd/jx-gitops_gc.md
  docs/cmd/jx-gitops_gc_jobs.md
  docs/man/man1/jx-gitops-gc-jobs.1
  docs/man/man1/jx-gitops-gc.1
  pkg/cmd/gc/gc.go
  pkg/cmd/gc/jobs/jobs.go
Labels: approved, lgtm, size/L, ok-to-test
