Repository jenkins-x-plugins/jx-gitops, pull requests merged in 2021-04, with the labels that each got.

#715 fix: upgrade deps
  go.mod
  go.sum
Labels: approved, size/M

#716 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/XS

#717 fix: lets try the latest helmfile
  pkg/plugins/versions.go
Labels: approved, size/XS

#720 chore: disable test in CI
  pkg/cmd/helm/mirror/mirror_test.go
Labels: approved, size/XS

#726 fix: lets ignore terraform environment requirements
  pkg/cmd/requirement/merge/merge.go
  pkg/cmd/requirement/merge/test_data/gke-ignore-env/changes.yml
  pkg/cmd/requirement/merge/test_data/gke-ignore-env/expected.yml
  pkg/cmd/requirement/merge/test_data/gke-ignore-env/jx-requirements.yml
Labels: approved, size/L

#727 fix: improve the gitops upgrade of terraform
  pkg/cmd/requirement/merge/test_data/gke-no-secret/changes.yml
  pkg/cmd/requirement/merge/test_data/gke-no-secret/expected.yml
  pkg/cmd/requirement/merge/test_data/gke-no-secret/jx-requirements.yml
  pkg/tfupgrade/test_data/azure/expected.tf
  pkg/tfupgrade/test_data/azure/main.tf
  pkg/tfupgrade/test_data/azure/versionStream/git/github.com/jenkins-x-terraform/terraform-jx-azure.yml
  pkg/tfupgrade/test_data/eks/expected.tf
  pkg/tfupgrade/test_data/eks/main.tf
  pkg/tfupgrade/test_data/eks/versionStream/git/github.com/jenkins-x/terraform-aws-eks-jx.yml
  pkg/tfupgrade/test_data/gke/expected.tf
  pkg/tfupgrade/test_data/gke/main.tf
  pkg/tfupgrade/test_data/gke/versionStream/git/github.com/jenkins-x/terraform-google-jx.yml
  pkg/tfupgrade/tfupgrade.go
  pkg/tfupgrade/tfupgrade_test.go
Labels: approved, size/L

#729 fix: use a better approach to adding helm repos
  docs/cmd/jx-gitops_helmfile_resolve.md
  docs/config.md
  docs/man/man1/jx-gitops-helmfile-resolve.1
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/cmd/helmfile/resolve/resolve_test.go
  pkg/helmhelpers/helpers.go
Labels: approved, size/M

#730 fix: add command to modify yaml files
  docs/cmd/jx-gitops.md
  docs/cmd/jx-gitops_yset.md
  docs/config.md
  docs/man/man1/jx-gitops-yset.1
  docs/man/man1/jx-gitops.1
  pkg/cmd/root.go
  pkg/cmd/yset/test_data/image_tag/expected.yaml
  pkg/cmd/yset/test_data/image_tag/source.yaml
  pkg/cmd/yset/test_data/missing_top_level/expected.yaml
  pkg/cmd/yset/test_data/missing_top_level/source.yaml
  pkg/cmd/yset/test_data/top_level/expected.yaml
  pkg/cmd/yset/test_data/top_level/source.yaml
  pkg/cmd/yset/yset.go
  pkg/cmd/yset/yset_test.go
  pkg/plugins/helpers.go
Labels: approved, size/XL

#731 fix: better logic for picking the plugin install dir
  pkg/plugins/helpers.go
Labels: approved, size/XS

#734 fix: lets put cluster resources into a sub dir
  go.mod
  go.sum
  pkg/cmd/helmfile/move/move.go
  pkg/cmd/helmfile/move/move_test.go
Labels: approved, size/S

#735 chore: include domain in the generated variables
  pkg/cmd/variables/variables.go
Labels: approved, size/XS

#737 fix: lets log a warning if a Chart.yaml is invalid
  pkg/cmd/helmfile/report/report.go
Labels: approved, size/XS

#739 fix: lets add a few more env vars
  go.mod
  go.sum
  pkg/cmd/variables/test_data/tests/empty/expected.sh
  pkg/cmd/variables/test_data/tests/existing/expected.sh
  pkg/cmd/variables/test_data/tests/nokube/expected.sh
  pkg/cmd/variables/variables.go
  pkg/cmd/variables/variables_test.go
  pkg/sourceconfigs/helpers_test.go
Labels: approved, size/L

#740 fix: lets log a warning if we can't discover the dashboard
  pkg/cmd/variables/variables.go
Labels: approved, size/XS

#741 fix: add optional helm Chart CRD generation
  go.mod
  go.sum
  pkg/cmd/helmfile/report/report.go
Labels: approved, size/L

#742 fix: better jx-charter support
  go.mod
  go.sum
  pkg/cmd/git/setup/setup_test.go
  pkg/cmd/git/setup/test_data/expected2.txt
  pkg/cmd/helmfile/report/report.go
Labels: approved, size/L

#743 fix: lets only include report releases which are used
  go.mod
  go.sum
  pkg/cmd/helmfile/report/report.go
Labels: approved, size/M

#744 fix: avoid using relative paths in Chart crd names
  go.mod
  go.sum
  pkg/cmd/helmfile/report/report.go
Labels: approved, size/M

#745 fix: add chart repo name/url
  go.mod
  go.sum
  pkg/cmd/helmfile/report/report.go
  pkg/releasereport/types.go
Labels: approved, size/M
