Repository jenkins-x-plugins/jx-gitops, pull requests merged in 2021-02, with the labels that each got.

#568 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/S

#570 chore: make 'jx gitops helmfile report' fast
  go.mod
  go.sum
  pkg/cmd/helmfile/report/report.go
Labels: approved, size/M

#571 fix: upgrade helm and helmfile
  go.mod
  go.sum
  pkg/plugins/helpers.go
  pkg/plugins/helpers_test.go
  pkg/plugins/versions.go
Labels: approved, size/S

#572 chore: use latest greatest helmfile downloads
  docs/cmd/jx-gitops_helm_mirror.md
  docs/man/man1/jx-gitops-helm-mirror.1
  pkg/plugins/helpers.go
  pkg/plugins/helpers_test.go
Labels: approved, size/L

#575 fix: resolving relative version stream values files when specifying a different --helmfile flag and location
  pkg/cmd/helmfile/report/report.go
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/cmd/helmfile/resolve/resolve_test.go
  pkg/cmd/helmfile/resolve/test_data/helmfile_subfolder/.jx/gitops/secret-mappings.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_subfolder/expected-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_subfolder/expected-secret-infra-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_subfolder/extensions/pipeline-catalog.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_subfolder/extensions/quickstarts.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_subfolder/helmfiles/helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_subfolder/helmfiles/secret-infra/helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_subfolder/imagePullSecrets.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_subfolder/jx-requirements.yml
  pkg/cmd/helmfile/resolve/test_data/helmfile_subfolder/values/external-dns/values.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_subfolder/values/kubernetes-external-secrets/values.yaml.gotmpl
  pkg/cmd/helmfile/resolve/test_data/helmfile_subfolder/versionStream/charts/external-secrets/kubernetes-external-secrets/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_subfolder/versionStream/charts/repositories.yml
  pkg/cmd/helmfile/resolve/test_data/helmfile_subfolder/versionStream/git/github.com/jenkins-x/jx3-pipeline-catalog.yml
  pkg/cmd/helmfile/resolve/test_data/helmfile_subfolder/versionStream/git/github.com/jstrachan/jx3-pipeline-catalog.yml
  pkg/helmfiles/helpers.go
  pkg/jxtmpl/reqvalues/requirements_values.go
  pkg/jxtmpl/reqvalues/requirements_values_test.go
  pkg/jxtmpl/reqvalues/test_data/jx-global-values-expected.yaml
  pkg/jxtmpl/reqvalues/test_data/jx-global-values.yaml
Labels: approved, size/L

#579 fix: improve default VERSION
  pkg/variablefinders/version.go
Labels: approved, size/XS

#580 feat: added in resolve update check to inform user to migrate from gitops managed vault to terraform installed vault if one is detected
  go.mod
  go.sum
  pkg/cmd/helmfile/resolve/resolve.go
Labels: approved, ok-to-test, size/S

#595 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/M

#597 chore: add custom upgrade for external secrets chart
  go.mod
  go.sum
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/expected-secret-infra-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_multi_subfolder/expected-secret-infra-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_multi_subfolder/helmfiles/secret-infra/helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_subfolder/expected-secret-infra-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_subfolder/helmfiles/secret-infra/helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/input/expected-secret-infra-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/no-versionstream/expected-external-secrets-helmfile.yaml
Labels: approved, size/S

#602 chore: lets not always add the .lighthouse folder during upgrade, instead make it optional with a flag
  pkg/cmd/helmfile/resolve/resolve.go
Labels: approved, size/M

#608 feat: revert back to external-secrets main chart repo
  .lighthouse/jenkins-x/release.yaml
  go.mod
  go.sum
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/expected-secret-infra-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_multi_subfolder/expected-secret-infra-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_subfolder/expected-secret-infra-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/input/expected-secret-infra-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/no-versionstream/expected-external-secrets-helmfile.yaml
Labels: approved, size/M

#611 fix: lets add optional slack notification configuration
  go.mod
  go.sum
  pkg/apis/gitops/v1alpha1/source_config_types.go
  pkg/cmd/scheduler/scheduler_test.go
  pkg/sourceconfigs/helpers.go
  pkg/sourceconfigs/helpers_test.go
Labels: approved, size/L

#614 chore: fix bug in slack configuration
  pkg/apis/gitops/v1alpha1/source_config_types.go
  pkg/sourceconfigs/helpers_test.go
Labels: approved, size/M

#615 fix: avoid /hook/hook in webhook URL
  go.mod
  go.sum
  pkg/cmd/webhook/update/constants.go
  pkg/cmd/webhook/update/update.go
  pkg/cmd/webhook/update/update_test.go
  pkg/cmd/webhook/webhook.go
Labels: approved, size/M

#617 chore: upgrade deps
  go.mod
  go.sum
  pkg/variablefinders/requirements.go
  pkg/variablefinders/requirements_test.go
Labels: approved, size/S

#618 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/S

#621 fix: upgrade deps
  go.mod
  go.sum
Labels: approved, size/S
