Repository jenkins-x-plugins/jx-gitops, pull requests merged in 2021-03, with the labels that each got.

#631 fix: lets tone down the logging
  go.mod
  go.sum
  pkg/cmd/hash/hash.go
  pkg/cmd/helmfile/add/add.go
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/cmd/repository/create/create.go
  pkg/cmd/repository/resolve/resolve.go
  pkg/cmd/scheduler/scheduler.go
  pkg/pipelinescheduler/generator.go
Labels: approved, size/M

#635 fix: avoid duplicate namespaces in the report
  pkg/cmd/helmfile/report/report.go
Labels: approved, size/XS

#636 fix: lets migrate to the new jx-preview chart location
  go.mod
  go.sum
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/cmd/helmfile/resolve/test_data/local-secrets/expected-jx-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/helmfile.yaml
  pkg/cmd/requirement/merge/test_data/gke-v3/changes.yml
  pkg/cmd/requirement/merge/test_data/gke-v3/expected.yml
  pkg/cmd/requirement/merge/test_data/gke-v3/jx-requirements.yml
Labels: approved, size/L

#637 fix: avoid duplicates in the report
  pkg/cmd/git/setup/setup.go
  pkg/cmd/helmfile/report/report.go
Labels: approved, size/S

#638 chore: tone down logging for webhooks
  pkg/cmd/webhook/update/update.go
Labels: approved, size/XS

#647 fix: handle bitbucketserver upper case org names
  go.mod
  go.sum
  pkg/cmd/scheduler/scheduler.go
  pkg/cmd/scheduler/scheduler_test.go
  pkg/cmd/scheduler/test_data/config-root/namespaces/jx/jxboot-helmfile-resources/bbs-in-repo-sr.yaml
Labels: approved, size/M

#650 fix: migrate the chart to the v3 chart repo
  go.mod
  go.sum
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/expected-jx-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/versionStream/charts/jx3/jxboot-helmfile-resources/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/input/expected-jx-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/expected-jx-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/versionStream/charts/jx3/jxboot-helmfile-resources/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/no-versionstream/expected-jx-helmfile.yaml
Labels: approved, size/M

#655 fix: for bitbucket server
  go.mod
  go.sum
  pkg/cmd/pr/label/label.go
Labels: approved, size/S

#658 fix: upgrade go-scm
  go.mod
  go.sum
Labels: approved, size/XS

#662 fix: add username/pwd to helm release
  go.mod
  go.sum
  pkg/cmd/helm/release/release.go
  pkg/cmd/webhook/update/update.go
Labels: approved, size/M

#661 chore: expose prometheus metrics on lighthouse
  pkg/pipelinescheduler/config_builder.go
  pkg/pipelinescheduler/test_data/merger_with_mergemethod/config.yaml
  pkg/pipelinescheduler/test_data/merger_with_parent/config.yaml
  pkg/pipelinescheduler/test_data/multiple_contexts/config.yaml
  pkg/pipelinescheduler/test_data/no_postsubmits_with_parent/config.yaml
  pkg/pipelinescheduler/test_data/only_with_parent/config.yaml
  pkg/pipelinescheduler/test_data/policy_with_parent/config.yaml
  pkg/pipelinescheduler/test_data/repo/config.yaml
  pkg/pipelinescheduler/test_data/with_parent/config.yaml
Labels: approved, lgtm, ok-to-test, size/S

#666 fix: add optional push container registry
  pkg/cmd/variables/test_data/tests/empty/expected.sh
  pkg/cmd/variables/test_data/tests/existing/expected.sh
  pkg/cmd/variables/test_data/tests/nokube/expected.sh
  pkg/cmd/variables/variables.go
  pkg/cmd/variables/variables_test.go
Labels: approved, size/S

#672 fix: avoid using the old http URL for jx charts
  pkg/cmd/helm/test_data/versionstream/charts/repositories.yml
  pkg/cmd/helmfile/add/test_data/input/versionStream/charts/repositories.yml
  pkg/cmd/helmfile/report/test_data/releases.yaml
  pkg/cmd/helmfile/resolve/test_data/bucketrepo-svc/versionStream/charts/repositories.yml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/versionStream/charts/repositories.yml
  pkg/cmd/helmfile/resolve/test_data/helmfile_multi_subfolder/versionStream/charts/repositories.yml
  pkg/cmd/helmfile/resolve/test_data/helmfile_subfolder/versionStream/charts/repositories.yml
  pkg/cmd/helmfile/resolve/test_data/input/versionStream/charts/repositories.yml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/versionStream/charts/repositories.yml
  pkg/cmd/jenkins/add/test_data/versionStream/charts/repositories.yml
  pkg/cmd/jenkins/jobs/test_data/hasjobs/versionStream/charts/repositories.yml
  pkg/cmd/requirement/publish/test_data/config-root/namespaces/jx/jxboot-helmfile-resources/dev-environment.yaml
  pkg/cmd/scheduler/test_data/config-root/namespaces/jx/jxboot-helmfile-resources/devenv.yaml
  pkg/helmhelpers/helpers.go
Labels: approved, size/S

#675 fix: upgrade to the https URL for jenkins-x charts
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/cmd/helmfile/resolve/test_data/helmfile_subfolder/expected-secret-infra-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_subfolder/helmfiles/secret-infra/helmfile.yaml
Labels: approved, size/XS

#679 fix: upgrade deps
  go.mod
  go.sum
Labels: approved, size/S

#681 fix: handle missing hmac secret if using BBC
  go.mod
  go.sum
  pkg/cmd/webhook/update/update.go
Labels: approved, size/S

#682 fix: upgrade go-scm
  go.mod
  go.sum
  pkg/cmd/webhook/update/update.go
Labels: approved, size/S

#685 fix: annotate logic
  go.mod
  go.sum
  pkg/cmd/webhook/update/update.go
Labels: approved, size/S

#689 fix: upgrade go-scm
  go.mod
  go.sum
Labels: approved, size/XS

#693 fix: handle lighthouse moving to jx3
  go.mod
  go.sum
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/cmd/helmfile/resolve/test_data/local-secrets/expected-jx-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/helmfile.yaml
Labels: approved, size/M

#698 fix: upgrade deps
  go.mod
  go.sum
Labels: approved, size/S

#702 fix: upgrade helm
  pkg/plugins/versions.go
Labels: approved, size/XS

#704 fix: ignore remote git repository files
  pkg/cmd/gc/activities/activities_test.go
  pkg/cmd/requirement/merge/merge.go
  pkg/helmfiles/helpers.go
Labels: approved, size/XS

#707 fix: refactor the release report library
  pkg/cmd/helmfile/report/markdown.go
  pkg/cmd/helmfile/report/markdown_test.go
  pkg/cmd/helmfile/report/report.go
  pkg/cmd/helmfile/status/status.go
  pkg/releasereport/helpers.go
  pkg/releasereport/types.go
Labels: approved, size/M

#710 fix: avoid failing if using OCI repository
  pkg/cmd/helmfile/report/report.go
Labels: approved, size/XS

#708 fix: hooks should also include deployment events
  go.mod
  go.sum
  pkg/cmd/webhook/update/update.go
Labels: approved, lgtm, size/L
