Repository jenkins-x-plugins/jx-gitops, pull requests merged in 2021-11, with the labels that each got.

#815 fix: check for error when deleting tkn prs
  pkg/cmd/gc/activities/activities.go
Labels: approved, lgtm, size/XS

#816 fix: delete lj and tkn prs for pas which exceed revision history
  pkg/cmd/gc/activities/activities.go
Labels: size/M, approved, lgtm

#811 feat: Install/upgrade helm-s3 plugin
  pkg/cmd/plugin/upgrade/upgrade.go
  pkg/plugins/versions.go
Labels: size/M, approved, lgtm, ok-to-test

#817 fix: only warn on not being able to delete pipelineruns
  pkg/cmd/gc/activities/activities.go
Labels: approved, size/XS

#804 fix: Default username to user not owner
  pkg/cmd/helm/release/release.go
Labels: approved, lgtm, size/XS, ok-to-test

#818 refactor: Split out func GetSettings from FindRequirements
  go.mod
  go.sum
  pkg/variablefinders/requirements.go
Labels: approved, lgtm, size/L, ok-to-test
