Repository jenkins-x-plugins/jx-gitops, pull requests merged in 2021-06, with the labels that each got.

#774 fix: allow a custom chart secret to be used when releasing charts
  go.mod
  go.sum
  pkg/cmd/helm/release/release.go
Labels: approved, size/S

#777 fix: ensure the registry name is in lowercase
  pkg/cmd/variables/variables.go
  pkg/cmd/variables/variables_test.go
Labels: approved, lgtm, ok-to-test, size/XS

#779 chore: tone down logging
  pkg/cmd/helmfile/resolve/resolve_test.go
  pkg/cmd/helmfile/resolve/test_data/remote-cluster/.jx/gitops/secret-mappings.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-cluster/expected-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-cluster/expected-nginx-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-cluster/extensions/pipeline-catalog.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-cluster/extensions/quickstarts.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-cluster/helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-cluster/imagePullSecrets.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-cluster/jx-requirements.yml
  pkg/cmd/helmfile/resolve/test_data/remote-cluster/versionStream/charts/ingress-nginx/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-cluster/versionStream/charts/ingress-nginx/values.yaml.gotmpl
  pkg/cmd/helmfile/resolve/test_data/remote-cluster/versionStream/charts/jenkins-x/jxboot-helmfile-resources/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-cluster/versionStream/charts/jenkins-x/lighthouse/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-cluster/versionStream/charts/jenkins-x/tekton/defaults.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-cluster/versionStream/charts/jenkins-x/tekton/values.yaml.gotmpl
  pkg/cmd/helmfile/resolve/test_data/remote-cluster/versionStream/charts/repositories.yml
  pkg/cmd/helmfile/resolve/test_data/remote-cluster/versionStream/git/github.com/jenkins-x/jx3-pipeline-catalog.yml
  pkg/cmd/helmfile/resolve/test_data/remote-cluster/versionStream/git/github.com/jstrachan/jx3-pipeline-catalog.yml
  pkg/cmd/yset/yset.go
Labels: approved, size/L

#780 fix: add GHA test
  .github/workflows/plugins-pr.yaml
  go.mod
  go.sum
Labels: approved, size/M

#781 chore: polish docs
  .github/workflows/plugins-pr.yaml
  README.md
  go.mod
  go.sum
Labels: approved, size/S

#782 fix: upgrade dependencies
  go.mod
  go.sum
  pkg/cmd/helmfile/report/report.go
  pkg/cmd/ingress/ingress.go
  pkg/cmd/ingress/ingress_test.go
  pkg/cmd/ingress/test_data/notls/expected/namespaces/myapps/modify-ingress.yaml
  pkg/cmd/ingress/test_data/notls/expected/namespaces/myapps/modify-old-ingress.yaml
  pkg/cmd/ingress/test_data/notls/expected/namespaces/myapps/not-modify-ingress.yaml
  pkg/cmd/ingress/test_data/notls/expected/namespaces/myapps/service.yaml
  pkg/cmd/ingress/test_data/notls/source/config-root/namespaces/myapps/modify-ingress.yaml
  pkg/cmd/ingress/test_data/tls/expected/namespaces/myapps/modify-ingress.yaml
  pkg/cmd/ingress/test_data/tls/expected/namespaces/myapps/modify-old-ingress.yaml
  pkg/cmd/ingress/test_data/tls/expected/namespaces/myapps/not-modify-ingress.yaml
  pkg/cmd/ingress/test_data/tls/expected/namespaces/myapps/service.yaml
  pkg/cmd/ingress/test_data/tls/source/config-root/namespaces/myapps/modify-ingress.yaml
  pkg/cmd/variables/variables.go
  pkg/variablefinders/helpers.go
Labels: approved, size/L

#783 fix: lets migrate to the jx github chart repo
  go.mod
  go.sum
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/cmd/helmfile/resolve/resolve_test.go
  pkg/cmd/helmfile/resolve/test_data/bucketrepo-svc/expected-jx-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/expected-jx-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/custom-env-ingress/expected-jx-staging-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_multi_subfolder/expected-kuberhealthy-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_multi_subfolder/expected-secret-infra-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_subfolder/expected-secret-infra-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/input/expected-jx-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/expected-jx-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/local-secrets/expected-secret-infra-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/no-versionstream/expected-jx-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-chart/expected-foo-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-chart/expected-jx-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/remote-cluster/expected-nginx-helmfile.yaml
Labels: approved, size/L

#784 fix: remove old jx3 from chart values when migrating
  go.mod
  go.sum
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/cmd/helmfile/resolve/resolve_test.go
  pkg/cmd/helmfile/resolve/test_data/helmfile_multi_subfolder/expected-kuberhealthy-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_subfolder/expected-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_subfolder/expected-jx-helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_subfolder/helmfiles/helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_subfolder/helmfiles/jx/helmfile.yaml
  pkg/cmd/helmfile/resolve/test_data/helmfile_subfolder/helmfiles/jx/jx-values.yaml
Labels: approved, size/L
