Repository jenkins-x-plugins/jx-gitops, pull requests merged in 2021-01, with the labels that each got.

#489 feat: added in helmfile plugin bump to a fork that allows OCI based registries
  go.mod
  go.sum
  pkg/helmhelpers/helpers.go
  pkg/plugins/helpers.go
  pkg/plugins/helpers_test.go
  pkg/plugins/versions.go
Labels: approved, lgtm, ok-to-test, size/M

#497 chore: bump jx-api version
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test, size/XS

#500 fix: upgrade deps
  go.mod
  go.sum
  pkg/cmd/helm/release/release.go
  pkg/cmd/rename/rename.go
  pkg/cmd/requirement/merge/test_data/azure/expected.yml
  pkg/cmd/requirement/merge/test_data/azure/jx-requirements.yml
  pkg/cmd/requirement/merge/test_data/eks/expected.yml
  pkg/cmd/requirement/merge/test_data/gke-no-domain/expected.yml
  pkg/cmd/requirement/merge/test_data/gke/expected.yml
  pkg/cmd/requirement/merge/test_data/sample/expected.yml
  pkg/cmd/variables/variables.go
Labels: approved, size/M

#504 chore: add a halem value file to enable kuberhealth conditional healt…
  go.mod
  go.sum
  pkg/jxtmpl/reqvalues/requirements_values.go
Labels: approved, size/S

#505 chore: add additional top level conditional value for TLS check as you cannot combine multiple conditional values in helmfiles
  pkg/jxtmpl/reqvalues/requirements_values.go
Labels: approved, size/XS

#507 chore: upgarde jx-helpers
  go.mod
  go.sum
Labels: approved, size/L

#509 fix: upgrade deps
  go.mod
  go.sum
  pkg/cmd/pr/label/label_test.go
  pkg/cmd/variables/variables.go
Labels: approved, size/L

#511 fix: better handling of default chart repository
  pkg/cmd/helm/release/release.go
  pkg/cmd/variables/test_data/tests/nokube/expected.sh
  pkg/cmd/variables/variables.go
  pkg/cmd/variables/variables_test.go
  pkg/variablefinders/repo_url.go
Labels: approved, size/L

#512 fix: upgrade helm
  pkg/plugins/versions.go
Labels: approved, size/XS

#516 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/S

#517 fix: add github pages helm charts
  go.mod
  go.sum
  pkg/cmd/helm/release/release.go
  pkg/cmd/requirement/merge/test_data/azure/expected.yml
  pkg/cmd/requirement/merge/test_data/azure/jx-requirements.yml
  pkg/cmd/variables/test_data/tests/nokube/expected.sh
  pkg/cmd/variables/variables.go
  pkg/variablefinders/repo_url.go
Labels: approved, lgtm, size/L

#520 fix: set the remote url for helm chart github pages
  pkg/cmd/helm/release/release.go
Labels: approved, size/XS

#523 fix: add settings support
  go.mod
  go.sum
  pkg/cmd/helm/release/release.go
  pkg/cmd/variables/variables.go
  pkg/variablefinders/requirements.go
  pkg/variablefinders/requirements_test.go
  pkg/variablefinders/test_data/all/.jx/settings.yaml
  pkg/variablefinders/test_data/all/dev-env/jx-requirements.yml
  pkg/variablefinders/test_data/all/expected.yml
  pkg/variablefinders/test_data/chart_repo/.jx/settings.yaml
  pkg/variablefinders/test_data/chart_repo/dev-env/jx-requirements.yml
  pkg/variablefinders/test_data/chart_repo/expected.yml
  pkg/variablefinders/test_data/no_settings/dev-env/jx-requirements.yml
  pkg/variablefinders/test_data/no_settings/expected.yml
Labels: approved, size/XL

#525 fix: make 'jx gitops git setup' usable in GHA
  pkg/cmd/git/setup/setup.go
Labels: approved, size/S

#526 fix: if domain is set in terraform always use that to override cluster requirements as domains are managed by Terraform
  pkg/cmd/requirement/merge/merge.go
  pkg/cmd/requirement/merge/test_data/domain/changes.yml
  pkg/cmd/requirement/merge/test_data/domain/expected.yml
  pkg/cmd/requirement/merge/test_data/domain/jx-requirements.yml
Labels: approved, size/L

#530 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: size/S, updatebot

#532 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: updatebot

#534 fix: upgrade k8s dependencies
  go.mod
  go.sum
  pkg/cmd/copy/copy_test.go
Labels: approved, size/L

#537 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: size/L, updatebot

#550 feat: install helm-x plugin during gitops plugin upgrade
  pkg/cmd/plugin/upgrade/upgrade.go
Labels: approved, lgtm, ok-to-test, size/S

#551 chore: upgrade pipelines
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/L, updatebot

#553 fix: lets disable helm-x on ARM
  go.mod
  go.sum
  pkg/cmd/plugin/upgrade/upgrade.go
  pkg/cmd/scheduler/test_data/versionStream/schedulers/in-repo.yaml
Labels: approved, size/M

#554 fix: pipeline
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  pkg/cmd/repository/resolve/resolve.go
Labels: approved, size/XS

#556 chore: more debugging while making jx-boot image
  pkg/cmd/plugin/upgrade/upgrade.go
Labels: approved, size/XS

#557 chore: helmfile dep bump
  go.mod
  go.sum
  pkg/plugins/versions.go
Labels: approved, lgtm, ok-to-test, size/S

#558 chore: temporary disable of helm-x install
  pkg/cmd/plugin/upgrade/upgrade.go
  pkg/cmd/variables/variables_test.go
Labels: approved, size/M

#563 chore: re-enable helm-x
  go.mod
  go.sum
  pkg/cmd/plugin/upgrade/upgrade.go
Labels: approved, size/M

#564 fix: support $ character in variable values
  pkg/cmd/variables/test_data/tests/empty/expected.sh
  pkg/cmd/variables/test_data/tests/existing/.jx/variables.sh
  pkg/cmd/variables/test_data/tests/existing/expected.sh
  pkg/cmd/variables/test_data/tests/nokube/expected.sh
  pkg/cmd/variables/variables.go
Labels: approved, lgtm, ok-to-test, size/M

#565 fix: polish helm github pages
  go.mod
  go.sum
  pkg/cmd/helm/release/release.go
  pkg/ghpages/ghpages.go
Labels: approved, size/S

#566 fix: ask Git providers to notify Lighthouse about Review events
  pkg/cmd/webhook/verify/verify.go
Labels: approved, lgtm, ok-to-test, size/XS
