Repository jenkins-x-plugins/jx-gitops, pull requests merged in 2022-09, with the labels that each got.

#880 feat: include chart name and version in commits for pages chart repos
  cmd/app/main-win.go
  cmd/app/main.go
  pkg/cmd/gc/activities/activities_test.go
  pkg/cmd/git/merge/pull_refs_test.go
  pkg/cmd/helm/release/release.go
  pkg/cmd/helm/release/release_test.go
  pkg/cmd/helm/release/testdata/pages/README.md
  pkg/cmd/requirement/edit/edit_test.go
  pkg/pipelinescheduler/builder_test.go
  pkg/pipelinescheduler/config_builder_test.go
Labels: approved, lgtm, size/L, ok-to-test

#883 fix: Show links better
  pkg/cmd/helmfile/report/markdown.go
  pkg/cmd/helmfile/report/testdata/expected.README.md
Labels: size/M, approved

#884 revert: Regen on new cluster
  pkg/cmd/apply/apply.go
Labels: size/M, approved

#886 feat: add supply chain security
  .gitignore
  .goreleaser.yml
  .lighthouse/jenkins-x/release.yaml
Labels: size/M, approved, lgtm, ok-to-test

#887 fix: replace / in nested gitlab repos with - to fix slack issues
  pkg/sourceconfigs/helpers.go
  pkg/sourceconfigs/helpers_test.go
Labels: approved, lgtm, size/S

#885 chore: upgrade helmfile plugin binary to 0.144.0
  pkg/plugins/versions.go
Labels: approved, lgtm, size/XS, ok-to-test

#891 fix: Regen on new cluster
  pkg/cmd/apply/apply.go
Labels: size/M, approved

#889 refactor: move to helmfile org
  go.mod
  go.sum
  pkg/cmd/annotate/testdata/cert-manager-bug/expected.yaml
  pkg/cmd/annotate/testdata/cert-manager-bug/source.yaml
  pkg/cmd/annotate/testdata/cluster-role-binding/expected.yaml
  pkg/cmd/annotate/testdata/cluster-role-binding/source.yaml
  pkg/cmd/annotate/testdata/svc/expected.yaml
  pkg/cmd/annotate/testdata/svc/source.yaml
  pkg/cmd/helmfile/move/move.go
  pkg/cmd/helmfile/report/report.go
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/cmd/helmfile/resolve/resolve_test.go
  pkg/cmd/helmfile/structure/structure.go
  pkg/cmd/helmfile/validate/validate.go
  pkg/cmd/image/testdata/expected/src/deployment.yaml
  pkg/cmd/image/testdata/expected/src/job.yaml
  pkg/cmd/image/testdata/expected/src/pipelinerun-with-task.yml
  pkg/cmd/image/testdata/expected/src/tasks.yaml
  pkg/cmd/ingress/testdata/notls/expected/namespaces/myapps/modify-ingress.yaml
  pkg/cmd/ingress/testdata/notls/expected/namespaces/myapps/modify-old-ingress.yaml
  pkg/cmd/ingress/testdata/notls/source/config-root/namespaces/myapps/modify-ingress.yaml
  pkg/cmd/ingress/testdata/notls/source/config-root/namespaces/myapps/modify-old-ingress.yaml
  pkg/cmd/ingress/testdata/tls/expected/namespaces/myapps/modify-ingress.yaml
  pkg/cmd/ingress/testdata/tls/expected/namespaces/myapps/modify-old-ingress.yaml
  pkg/cmd/jenkins/add/add_test.go
  pkg/cmd/jenkins/jobs/jobs_test.go
  pkg/cmd/kustomize/testdata/expected/myapp/ingress.yaml
  pkg/cmd/kustomize/testdata/source/kustomization.yaml
  pkg/cmd/label/testdata/cluster-role-binding/expected.yaml
  pkg/cmd/label/testdata/cluster-role-binding/source.yaml
  pkg/cmd/label/testdata/svc/expected.yaml
  pkg/cmd/label/testdata/svc/source.yaml
  pkg/cmd/lint/lint.go
  pkg/cmd/namespace/namespace_test.go
  pkg/cmd/namespace/testdata/dirmode/something/cheese-svc.yaml
  pkg/cmd/namespace/testdata/regular/hasns/expected.yaml
  pkg/cmd/namespace/testdata/regular/hasns/source.yaml
  pkg/cmd/namespace/testdata/regular/nons/expected.yaml
  pkg/cmd/namespace/testdata/regular/nons/source.yaml
  pkg/helmfiles/add.go
  pkg/helmfiles/editor.go
  pkg/helmfiles/helpers.go
  pkg/helmhelpers/helpers.go
  pkg/helmhelpers/helpers_test.go
  pkg/plugins/helpers.go
  pkg/plugins/helpers_test.go
  pkg/plugins/versions.go
Labels: approved, size/XXL

#892 fix: Resources for release build
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/XS

#893 fix: Correct download url for helmfile
  .lighthouse/jenkins-x/lint.yaml
  pkg/plugins/helpers.go
  pkg/plugins/helpers_test.go
Labels: approved, size/S

#895 feat: Add option to select field to filter on
  go.mod
  go.sum
Labels: approved, size/XS

#874 fix: upgrade go to the latest go1.18
  .github/workflows/plugins-pr.yaml
  Makefile
  go.mod
  go.sum
Labels: approved, size/S, ok-to-test

#890 fix: helm release support for OCI registry
  pkg/cmd/helm/release/release.go
  pkg/cmd/helm/release/release_test.go
Labels: approved, size/L

#894 fix: use jenkins x org as default for pipeline catalog
  pkg/pipelinecatalogs/pipelinecatalogs.go
Labels: approved, size/XS
