Repository jenkins-x-plugins/jx-gitops, pull requests merged in 2022-06, with the labels that each got.

#854 chore(deps): Upgrade kpt
  pkg/plugins/versions.go
Labels: approved, size/XS

#856 fix: Correct namespace for resources
  pkg/cmd/git/merge/merge_shas.go
  pkg/cmd/helmfile/move/move.go
Labels: approved, size/L

#851 fix: pr comment variables
  pkg/cmd/pr/variables/variables.go
Labels: approved, size/XS, ok-to-test

#858 Revert "chore(deps): Upgrade kpt"
  pkg/plugins/versions.go
Labels: approved, size/XS

#857 fix: ListComments order of gitlab
  go.mod
  go.sum
  pkg/cmd/pr/variables/variables.go
Labels: approved, size/S, ok-to-test

#862 Revert "fix: Resources for release build"
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/XS

#864 chore(deps): Upgrade kpt
  pkg/cmd/plugin/upgrade/upgrade.go
  pkg/plugins/versions.go
Labels: approved, size/S
