Repository jenkins-x-plugins/jx-gitops, pull requests merged in 2022-03, with the labels that each got.

#825 feat: Add support for kustomize
  pkg/plugins/helpers.go
  pkg/plugins/versions.go
Labels: approved, lgtm, size/S, ok-to-test

#836 fix: Do not recreate namespace `jx-git-operator`
  pkg/cmd/namespace/namespace.go
Labels: approved, lgtm, size/XS, ok-to-test

#838 Revert "fix: Do not recreate namespace `jx-git-operator`"
  pkg/cmd/namespace/namespace.go
Labels: approved, lgtm, size/XS, ok-to-test

#839 refactor: use T.TempDir to create temporary test directory
  pkg/cmd/annotate/annotate_test.go
  pkg/cmd/git/clone/clone_test.go
  pkg/cmd/git/get/get_test.go
  pkg/cmd/git/merge/merge_test.go
  pkg/cmd/hash/hash_test.go
  pkg/cmd/helm/escape/escape_test.go
  pkg/cmd/helm/step_helm_template_test.go
  pkg/cmd/helmfile/add/add_test.go
  pkg/cmd/helmfile/deletecmd/delete_test.go
  pkg/cmd/helmfile/move/move_test.go
  pkg/cmd/helmfile/report/markdown_test.go
  pkg/cmd/helmfile/resolve/resolve_test.go
  pkg/cmd/helmfile/structure/structure_test.go
  pkg/cmd/helmfile/validate/validate_test.go
  pkg/cmd/image/image_test.go
  pkg/cmd/ingress/ingress_test.go
  pkg/cmd/jenkins/add/add_test.go
  pkg/cmd/jenkins/jobs/jobs_test.go
  pkg/cmd/label/label_test.go
  pkg/cmd/namespace/namespace_test.go
  pkg/cmd/pr/variables/variables_test.go
  pkg/cmd/rename/rename_test.go
  pkg/cmd/repository/add/add_test.go
  pkg/cmd/repository/create/create_test.go
  pkg/cmd/repository/deletecmd/delete_test.go
  pkg/cmd/repository/export/export_test.go
  pkg/cmd/repository/resolve/resolve_test.go
  pkg/cmd/requirement/edit/edit_test.go
  pkg/cmd/requirement/merge/merge_test.go
  pkg/cmd/requirement/publish/publish_test.go
  pkg/cmd/requirement/resolve/resolve_test.go
  pkg/cmd/sa/secret/secret_test.go
  pkg/cmd/scheduler/scheduler_test.go
  pkg/cmd/split/split_test.go
  pkg/cmd/variables/variables_test.go
  pkg/cmd/yset/yset_test.go
  pkg/tfupgrade/tfupgrade_test.go
  pkg/variablefinders/requirements_test.go
Labels: approved, size/L, ok-to-test
