Repository jenkins-x-plugins/jx-gitops, pull requests merged in 2022-08, with the labels that each got.

#852 chore: add GetFilteredGroups GetRepository GetRepositoryFor
  pkg/sourceconfigs/helpers.go
  pkg/sourceconfigs/helpers_test.go
Labels: size/M, approved, ok-to-test

#876 fix: Regen on new cluster
  pkg/cmd/apply/apply.go
Labels: size/M, approved

#882 fix: Hide broken icons
  go.mod
  go.sum
  pkg/cmd/helmfile/report/markdown.go
  pkg/cmd/helmfile/report/testdata/expected.README.md
Labels: approved, size/S
