Repository jenkins-x-plugins/jx-gitops, pull requests merged in 2023-03, with the labels that each got.

#917 fix: correct ingress details on custom namespaces
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/cmd/helmfile/resolve/resolve_test.go
  pkg/cmd/helmfile/resolve/testdata/custom-env-ingress/expected-helmfile.yaml
  pkg/cmd/helmfile/resolve/testdata/custom-env-ingress/helmfile.yaml
  pkg/cmd/helmfile/resolve/testdata/custom-env-ingress/jx-requirements.yml
Labels: size/M, approved, ok-to-test

#904 feat: don't update markdown if command doc isn't updated
  cmd/docs/md_docs.go
Labels: size/M, approved

#911 fix: field to distinguish repository groups
  pkg/apis/gitops/v1alpha1/source_config_types.go
Labels: approved, size/XS

#919 fix: set inactive deployment status & skip deployments that are unchanged
  pkg/cmd/helmfile/status/status.go
  pkg/cmd/helmfile/status/status_test.go
Labels: approved, size/L

#920 feat: support create/update deployment in remote cluster
  docs/cmd/jx-gitops_helmfile_status.md
  pkg/cmd/helmfile/status/status.go
  pkg/cmd/helmfile/status/status_test.go
  pkg/cmd/helmfile/status/testdata/docs/releases.yaml
Labels: approved, size/L

#921 feat: allow override of the default container tool
  pkg/cmd/kpt/update/update.go
Labels: approved, size/XS

#924 fix: force push pr with lease
  pkg/cmd/pr/push/push.go
Labels: approved, size/XS

#925 Support using repo from chart sources for setting deployment status
  pkg/cmd/helmfile/status/status.go
Labels: size/M, approved

#926 fix: force push pr with lease
  pkg/cmd/pr/push/push.go
Labels: approved, size/XS

#922 fix: correct sign of offset and negation of expression
  pkg/cmd/helmfile/status/status.go
  pkg/cmd/helmfile/status/status_test.go
  pkg/cmd/helmfile/status/testdata/docs/releases.yaml
Labels: size/M, approved

#928 fix: create new deployment on new ref
  pkg/cmd/helmfile/status/status.go
  pkg/cmd/helmfile/status/status_test.go
Labels: size/M, approved
