Repository jenkins-x-plugins/jx-gitops, pull requests merged in 2024-01, with the labels that each got.

#950 chore: upgrade helmfile to 0.149.0
  pkg/plugins/versions.go
Labels: approved, size/XS, ok-to-test

#951 feat(comment): allow to choose between 3 comment strategies
  pkg/cmd/pr/comment/comment.go
  pkg/cmd/pr/comment/comment_test.go
Labels: approved, size/L, ok-to-test

#952 chore: update docs
  docs/cmd/jx-gitops_annotate.md
  docs/cmd/jx-gitops_helmfile_move.md
  docs/cmd/jx-gitops_helmfile_status.md
  docs/cmd/jx-gitops_image.md
  docs/cmd/jx-gitops_kpt_update.md
  docs/cmd/jx-gitops_label.md
  docs/cmd/jx-gitops_namespace.md
  docs/cmd/jx-gitops_pr_comment.md
  docs/cmd/jx-gitops_repository_add.md
  docs/cmd/jx-gitops_repository_create.md
  docs/cmd/jx-gitops_repository_export.md
  docs/cmd/jx-gitops_repository_resolve.md
  docs/cmd/jx-gitops_sa_secret.md
  docs/cmd/jx-gitops_upgrade.md
  docs/config.md
  docs/man/man1/jx-gitops-annotate.1
  docs/man/man1/jx-gitops-helmfile-move.1
  docs/man/man1/jx-gitops-helmfile-status.1
  docs/man/man1/jx-gitops-image.1
  docs/man/man1/jx-gitops-kpt-update.1
  docs/man/man1/jx-gitops-label.1
  docs/man/man1/jx-gitops-namespace.1
  docs/man/man1/jx-gitops-pr-comment.1
  docs/man/man1/jx-gitops-repository-add.1
  docs/man/man1/jx-gitops-repository-create.1
  docs/man/man1/jx-gitops-repository-export.1
  docs/man/man1/jx-gitops-repository-resolve.1
  docs/man/man1/jx-gitops-sa-secret.1
  docs/man/man1/jx-gitops-upgrade.1
  docs/scheduler-config.md
Labels: approved, size/L
