Repository jenkins-x-plugins/jx-gitops, pull requests merged in 2024-06, with the labels that each got.

#962 chore: upgrade default helm version to 3.15.1
  pkg/plugins/versions.go
Labels: approved, size/XS, ok-to-test

#966 chore: upgrade to go 1.22
  .lighthouse/jenkins-x/lint.yaml
  .lighthouse/jenkins-x/pullrequest.yaml
  go.mod
  go.sum
  pkg/cmd/gc/activities/activities.go
  pkg/cmd/gc/activities/activities_test.go
Labels: approved, size/XXL

#965 feat: handle skip report comment config
  go.mod
  go.sum
  pkg/apis/scheduler/v1alpha1/types.go
  pkg/pipelinescheduler/builder.go
  pkg/pipelinescheduler/config_builder.go
Labels: approved, size/S, ok-to-test
