Repository jenkins-x-plugins/jx-gitops, pull requests merged in 2024-11, with the labels that each got.

#979 chore: add --no-push flag; set logic for mirror to git push
  pkg/cmd/helm/mirror/mirror.go
Labels: approved, size/S, ok-to-test

#973 feat: attempt partial clone of cluster repo when loading requirements
  pkg/cmd/helm/release/release_test.go
  pkg/sourceconfigs/helpers.go
  pkg/variablefinders/requirements.go
  pkg/variablefinders/requirements_test.go
Labels: size/M, approved, ok-to-test

#984 fix: optionally allow non-standard namespace
  Makefile
  docs/cmd/jx-gitops_helm.md
  docs/cmd/jx-gitops_helm_mirror.md
  docs/cmd/jx-gitops_helmfile_move.md
  docs/man/man1/jx-gitops-helm-mirror.1
  docs/man/man1/jx-gitops-helmfile-move.1
  pkg/cmd/helmfile/move/move.go
  pkg/cmd/helmfile/move/move_test.go
  pkg/cmd/helmfile/move/testdata/dirIncludesReleaseName/selenium-grid/selenium/keda/templates/keda-operator-auth-reader-rb.yaml
Labels: approved, size/L

#985 fix: Check out jx-requirements.yml from cluster repo upon sparse checkout
  pkg/cmd/helm/release/release_test.go
  pkg/variablefinders/requirements.go
Labels: approved, size/S, ok-to-test

#987 fix: make order of annotations stable
  pkg/cmd/helmfile/move/move.go
Labels: approved, size/S

#988 fix: move resource to directory for actual namespace
  pkg/cmd/helmfile/move/move.go
  pkg/cmd/helmfile/move/move_test.go
  pkg/cmd/helmfile/move/testdata/nonStandardNamespace/selenium-grid/selenium/keda/templates/keda-operator-auth-reader-rb.yaml
Labels: size/M, approved

#989 fix: handle quoted namespace in resource
  pkg/cmd/helmfile/move/move.go
  pkg/cmd/helmfile/move/move_test.go
  pkg/cmd/helmfile/move/testdata/nonStandardNamespace/selenium-grid/selenium/keda/templates/keda-operator-auth-reader-rb.yaml
Labels: size/M, approved

#909 Support OCI in helm charts with dependencies
  Dockerfile-preview
  pkg/cmd/helm/build/build.go
  pkg/cmd/helm/build/build_test.go
  pkg/cmd/helm/build/testdata/has_charts/charts/myapp/Chart.yaml
  pkg/cmd/helm/release/release.go
  pkg/cmd/helm/release/release_test.go
  pkg/cmd/helm/release/testdata/charts/myapp/Chart.yaml
  pkg/cmd/plugin/upgrade/upgrade.go
Labels: approved, size/L
