Repository jenkins-x-plugins/jx-gitops, pull requests merged in 2025-02, with the labels that each got.

#999 fix: prune reference to any values files removed from version stream
  pkg/cmd/helmfile/resolve/resolve.go
  pkg/cmd/helmfile/resolve/testdata/custom-env-ingress/expected-jx-helmfile.yaml
  pkg/cmd/helmfile/resolve/testdata/helmfile_multi_subfolder/expected-kuberhealthy-helmfile.yaml
  pkg/cmd/helmfile/resolve/testdata/helmfile_multi_subfolder/expected-secret-infra-helmfile.yaml
  pkg/cmd/helmfile/resolve/testdata/helmfile_remote/versionStream/charts/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl
  pkg/cmd/helmfile/resolve/testdata/helmfile_subfolder/expected-jx-helmfile.yaml
  pkg/cmd/helmfile/resolve/testdata/helmfile_subfolder/expected-secret-infra-helmfile.yaml
  pkg/cmd/helmfile/resolve/testdata/local-secrets/expected-jx-helmfile.yaml
  pkg/cmd/helmfile/resolve/testdata/remote-chart/expected-nginx-helmfile.yaml
  pkg/cmd/helmfile/resolve/testdata/remote-cluster/expected-nginx-helmfile.yaml
Labels: size/M, approved

#998 feat: allow display report completion duration
  go.mod
  go.sum
  pkg/apis/scheduler/v1alpha1/types.go
  pkg/pipelinescheduler/builder.go
  pkg/pipelinescheduler/config_builder.go
Labels: approved, size/S, ok-to-test

#1001 fix: correct usage of sub commands
  pkg/cmd/repository/create/create.go
  pkg/cmd/root.go
Labels: approved, size/S

#1003 Fix docs
  docs/cmd/jx-gitops_helm_build.md
  docs/cmd/jx-gitops_helmfile_validate.md
  docs/cmd/jx-gitops_plugin_upgrade.md
  docs/cmd/jx-gitops_postprocess.md
  docs/cmd/jx-gitops_repository_add.md
  docs/cmd/jx-gitops_repository_create.md
  docs/cmd/jx-gitops_repository_export.md
  docs/cmd/jx-gitops_sa_secret.md
  docs/cmd/jx-gitops_yset.md
  docs/config.md
  docs/man/man1/jx-gitops-helm-build.1
  docs/man/man1/jx-gitops-helmfile-validate.1
  docs/man/man1/jx-gitops-plugin-upgrade.1
  docs/man/man1/jx-gitops-postprocess.1
  docs/man/man1/jx-gitops-repository-add.1
  docs/man/man1/jx-gitops-repository-create.1
  docs/man/man1/jx-gitops-repository-export.1
  docs/man/man1/jx-gitops-sa-secret.1
  docs/man/man1/jx-gitops-yset.1
  docs/scheduler-config.md
  pkg/cmd/condition/condition.go
  pkg/cmd/copy/copy.go
  pkg/cmd/helmfile/add/add.go
  pkg/cmd/helmfile/validate/validate.go
  pkg/cmd/image/image.go
  pkg/cmd/namespace/namespace.go
  pkg/cmd/patch/patch.go
  pkg/cmd/postprocess/postprocess.go
  pkg/cmd/pr/label/label.go
  pkg/cmd/repository/add/add.go
  pkg/cmd/repository/export/export.go
  pkg/cmd/repository/resolve/resolve.go
  pkg/cmd/requirement/merge/merge.go
  pkg/cmd/root.go
  pkg/cmd/sa/secret/secret.go
  pkg/cmd/versionstream/versionstream.go
  pkg/cmd/webhook/delete/delete.go
  pkg/cmd/webhook/update/update.go
  pkg/cmd/yset/yset.go
Labels: approved, size/L
