Repository jenkins-x-plugins/jx-gitops, pull requests merged in 2025-06, with the labels that each got.

#1012 Chore use latest lighthouse client with tekton 0.69.1
  go.mod
  go.sum
  pkg/cmd/gc/activities/activities.go
  pkg/cmd/gc/activities/activities_test.go
Labels: approved, size/L

#1020 chore: upgrade tekton pipeline
  go.mod
  go.sum
Labels: approved, size/L

#1021 chore: debug release problem
  .lighthouse/jenkins-x/release.yaml
Labels: size/S

#1022 Revert "chore: debug release problem"
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/S
